### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SantosJMM** [kondratyev-nv/vscode-python-test-adapter#115]
- Issue Type: `Performance`
- Extension Name: `vscode-python-test-adapter`
- Extension Version: `0.3.15`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\smarte\littlefoxteam.vscode-python-test-adapter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kondratyev-nv** [comment]
@SantosJMM Thank you for the issue and sorry for the late reply! Can you please attach `C:\Users\smarte\littlefoxteam.vscode-python-test-adapter-unresponsive.cpuprofile.txt` file to the issue? Also, can you provide additional information? Like what test framework are you using? How many tests do you have? How long does it take for your tests to be discovered/completed without extension (for example, from command line)?

**Comment by Ardin1** [comment]
https://hqporner.com/hdporn/95503-the_only_way_to_help_my_husband_is_to_fuck_his_boss.html
