### ISSUE TITLE
What goes in the launch.json for debugging?

### ISSUE THREAD

**Issue by klaasjanelzinga** [kondratyev-nv/vscode-python-test-adapter#116]
Hi,

I am trying to use your extension in code, the Run works fine, but Debug gives a message:

     Invalid message: "console" must be one of:
     ["internalConsole, "integratedTerminal",  "externalTerminal"]

I tried multiple configs in the `launch.json` but I cannot get it to work. Do you have a sample launch.json?

contents of launch.json:

```
 {
   "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "internalConsole"
        }
]
}
```

**Comment by claytonlemons** [comment]
I just ran into this issue as well after a fresh installation of the plugin. 
I believe I tracked the problem down to this [line of code](https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/master/src/pythonTestAdapter.ts#L103). Since 'none' is not a valid value for `console` in a debug configuration, vscode reports the above error message.

**Comment by kondratyev-nv** [comment]
@klaasjanelzinga @claytonlemons Thank you for the issue! I have not saw any errors on this. For me debug silently stops without any pauses on a breakpoint, messages or errors. However, changing `console` to `internalConsole` helped. I will create a PR to fix this.

**Comment by claytonlemons** [comment]
For what it's worth, below is the vscode I'm using. Perhaps that would explain the differences in behavior.
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-74-generic
```

**Comment by claytonlemons** [comment]
@kondratyev-nv I fixed the issue in my local fork, since I need this feature now. Have you already created a PR, or would it help if I submit one?

**Comment by kondratyev-nv** [comment]
@claytonlemons Sorry for the late reply. Yeah, I've already created and merged PR, fogot to add a link to the issue, this is why you did not saw it. 

@klaasjanelzinga @claytonlemons I've just published a new version 0.3.16 with the fix. Please, update and let me know if the issue persists.

**Comment by kondratyev-nv** [comment]
@klaasjanelzinga Also, regarding your original question. I belive the problem was with the `console` value specified in the extension's code, not your launch.json. Moreover, when you debugging from the Test Explorer you don't need a launch.json file.

**Comment by klaasjanelzinga** [comment]
Thanks a lot! Will give it a try.
