### ISSUE TITLE
Discovering tests fail

### ISSUE THREAD

**Issue by VitaKop** [kondratyev-nv/vscode-python-test-adapter#118]
Hi,
discovering test fails on:
![image](https://user-images.githubusercontent.com/20167932/72510373-00cb0400-3852-11ea-9026-920603e880b8.png)
all tests pass  and discovered with python for vs code. also I don't have indication on which file to look at.

**Comment by kondratyev-nv** [comment]
@VitaKop Thank you for the issue! Is it possible for you to provide some small example to reproduce the issue? Also, just to make sure, are the Python path and version correct?

**Comment by VitaKop** [comment]
Here are my settings:
{
    "python.pythonPath": "C:\\Python27\\python.exe",
    "terminal.integrated.env.windows": {
        "PYTHONPATH" : "${workspaceRoot};${workspaceRoot}\\infrastructure;${workspaceRoot}\\logic;${workspaceRoot}\\common",      
    },
    "python.testing.unittestArgs": [
        "-v",
        "-s",
        ".\\UPS",
        "-p",
        "*Test.py"
    ],
    "files.exclude": {
        "**/*.pyc": true,
        "**/*.map": true,
        "**/*__pycache__": true,
    },
    "python.testing.pytestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.unittestEnabled": true,
}

unfortunately I can't share my code since it's restricted. I wish the error could point to the file (it points to the line but I have hundreds of files in my project).

**Comment by wobweger** [comment]
got the same problem
![tstExp_20200126_101846](https://user-images.githubusercontent.com/40311784/73133174-6757db00-4025-11ea-9912-445d5846f1a8.png)

as soon I import 
+ numpy 
+ pandas 
tests aren't discovered anymore 

![tstExp_20200126_101912](https://user-images.githubusercontent.com/40311784/73133176-69ba3500-4025-11ea-860a-ee086b938ce8.png)

run anaconda 3.7 64 bit on Win10

**Comment by kondratyev-nv** [comment]
@wobweger Judging by your screenshots, it looks like the tests in Test Explorer panel are not discovered at all, even with commented imports. Have you tried to consult the `Python Test Adapter Log` in the Output panel? Do you have the same error message as in the original issue description?

However, if your question is about Python panel in the sidebar you should address it to the Python extension - https://github.com/microsoft/vscode-python.

**Comment by kondratyev-nv** [comment]
@VitaKop In the latest version 0.3.17 I have added better discovery error reporting. This should help with the understanding of what went wrong during test collection. My guess for a reason behind the error you see in the log would be that in one of the tests the `id` member can be overridden. For example,
```
class InvalidTestIdTests(unittest.TestCase):
    def __init__(self, methodName):
        unittest.TestCase.__init__(self, methodName)
        self.id = 123
```
This is also the issue with the Python extension test discovery. However, with the latest release, the discovery should complete, and you will see invalid test cases in the list of the tests
![image](https://user-images.githubusercontent.com/4085884/73329367-8301f200-426e-11ea-85d2-1a3b64a4fc35.png)

Please, update and let me know if the issue persists.
