### ISSUE TITLE
Test explorer icon does not appear on the left

### ISSUE THREAD

**Issue by areebkhan91** [kondratyev-nv/vscode-python-test-adapter#125]
The icon for thest explorer disappeared.

<img width="1044" alt="Screen Shot 2020-02-08 at 9 35 16 PM" src="https://user-images.githubusercontent.com/20706131/74096973-06b3ae00-4abb-11ea-87a1-90a90dd99d50.png">

**Comment by kondratyev-nv** [comment]
@areebkhan91 Thank you for the issue! Unfortunately it looks like an issue in the Test Explorer UI https://github.com/hbenl/vscode-test-explorer/issues/113. Adding `"testExplorer.hideWhenEmpty": false` to the user setting and restarting VSCode should help for now.

**Comment by areebkhan91** [comment]
That solved it, thanks for the prompt response.

**Comment by hbenl** [comment]
Sorry about the confusing default behavior in Test Explorer 2.16.0, version 2.17.0 changes the default behavior back to never hide it.
