### ISSUE TITLE
can't list the testcase based on unittest in the Python View.

### ISSUE THREAD

**Issue by jxliaocb** [kondratyev-nv/vscode-python-test-adapter#127]
Issue Type: <b>Bug</b>

WIN7 x64 Python3.7.4 64bit (base':conda)
settings.json file content:

{
    "python.pythonPath": "D:\\Anaconda3\\python.exe",
    "python.workspaceSymbols.ctagsPath": "D:\\ctags58\\ctags58.exe",
    "python.testing.unittestArgs": [
        "-v",
        "-s",
        "./__pycache__",
        "-p",
        "*test*.py"
    ],
    "python.testing.pytestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.unittestEnabled": true
}

Extension version: 0.3.17
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (11.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by jxliaocb** [comment]
T
[python_unittest_test.zip](https://github.com/kondratyev-nv/vscode-python-test-adapter/files/4185383/python_unittest_test.zip)
he attachment is the test code.

**Comment by kondratyev-nv** [comment]
@jxliaocb Thank you for the issue! Can you please explain what would be the expected behavior and how it differs from the actual one? Also, `"-s", "./__pycache__"` does not look right. Shouldn't it be `"-s", "."` or another start directory?

**Comment by jxliaocb** [comment]
"./__pycache__"  change to .  is ok. 

Thanks
