### ISSUE TITLE
To many buttons to run Tests

### ISSUE THREAD

**Issue by StefanIGit** [kondratyev-nv/vscode-python-test-adapter#129]
I guess I did something wrong but I cannot figure out what.
I installed/enabled the extension "Python Test Explorer..."
which requires "Test Explorer UI"
I think I configured it correctly
`{
    "python.pythonPath": ".venv/bin/python3",
    "python.linting.pylintEnabled": false,
    "python.linting.enabled": true,
    "python.linting.pycodestyleEnabled": true,
    "python.linting.pylintUseMinimalCheckers": false,
    "python.testing.pytestArgs": [
        ".",
        "-v",
        "--disable-pytest-warnings",
        "--html=report.html"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.testing.autoTestDiscoverOnSaveEnabled": true
}`
but I have 2 run and 2 debug buttons over every test
Run Test and Run Debug are from Test Explorer UI
and Run Debug Show... are from Python Test...
Is  this a bug or feature? 
What did I do wrong? I guess I should only see the 2nd set.

![image](https://user-images.githubusercontent.com/15795837/74923009-5dc95500-53d0-11ea-8b97-b8e43529802b.png)

**Comment by kondratyev-nv** [comment]
@StefanIGit Thank you for the issue! Unfortunately, you did nothing wrong. Microsoft’s Python extension goes with built-in test explorer sidebar and CodeLens adornments. There is no setting to disabled them at the moment, see a Note at Test discovery section of the documentation https://code.visualstudio.com/docs/python/testing#_test-discovery. The Test Explorer UI extension has a setting `testExplorer.codeLens`, so there is a way to disable CodeLenses for Test Explorer UI if you want. Even though this doesn’t look right this is the default behavior and I don’t see any nice way to change it. However, if you have any ideas, I would be glad to collaborate.

**Comment by StefanIGit** [comment]
Hi, thx for the reply.
Even if feels odd I have to disable the `testExplorer.codeLens` it helps me here.
I'm not native English so I did not think that this ... buttons are called adornments. And the screenshots are looking correct. Hmm classical tl'dr, sorry.
I have no better Idea how to handle this, mostly to my almost complete lack of knowledge in vscode works.

**Comment by nzig** [comment]
If anyone finds this issue later, this is what worked for me:
```json
{
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": false,
    "pythonTestExplorer.testFramework": "pytest"
}
```
This disables all of the Python extension's testing features, but keeps this extension's.

**Comment by kondratyev-nv** [comment]
@nzig Thanks! I've added your solution to the [README](https://github.com/kondratyev-nv/vscode-python-test-adapter#2-how-to-use-this-extesion-to-run-django-tests).
