### ISSUE TITLE
Disable JustMyCode in python unit test

### ISSUE THREAD

**Issue by dingbx** [kondratyev-nv/vscode-python-test-adapter#139]
I'm using the python-test-adapter to debug unit test, but it seems that there is not a switch to turn off JustMyCode?

**Comment by kondratyev-nv** [comment]
@dingbx Thank you for the issue! Unfortunately, right now `justMyCode` parameter can only be set in launch.json file which does not affect Python test execution from the Test Explorer sidebar. As for now, I might suggest using debugging from the Python extension.

In the meantime, I'll take a look at what I can do to improve the debugging configuration for the Python Test Adapter.

**Comment by jamilraichouni** [comment]
Would really help if the Python test execution from the Test Explorer sidebar considers debug configs defined in the `launch.json` file.

Seems to be the same problem causing #167

**Comment by kondratyev-nv** [comment]
@dingbx I've just published a new version 0.4.5 with loading debug options from launch.json. At this point the following debug options are loaded:

- env
- stopOnEntry
- showReturnValue
- redirectOutput
- debugStdLib
- justMyCode
- subProcess

The extension will look for a launch.json configuration with `"type": "python"` and `"request": "test"` to load any of those options. Please, update and let me know if the issue persists.

**Comment by kondratyev-nv** [comment]
@dingbx I’m closing this issue. If debugging is not working for you, please feel free to reopen and comment.
