### ISSUE TITLE
Add an additional config variable that can override the test platform of vscode-python just for this addon

### ISSUE THREAD

**Issue by jakegt1** [kondratyev-nv/vscode-python-test-adapter#14]
I suggest that this adapter should be able to override vscode-python's choice of unit test platform.

We could have a config variable like this
```javascript
// When config var is set
vscode-python-test-adapter.unitTestPlatform = "unittest";
// Use unittest for python test explorer, vscode-python uses its own settings

// when config var is not set
vscode-python-test-adapter.unitTestPlatform = null;

// deduce unitTestPlatform by vscode-python settings
```

This would allow people, before this adapter has pytest/nosetest support, to continue using pytest/nosetest in tandem with this adapter if their code happens to have tests that default unittest supports. Personally, i use pytest in my day to day just because the result is that comes out of vscode python's test log is much more useful then unittest or nosetest, despite following unittest conventions.

**Comment by darkvertex** [comment]
I concur. I think this is a really good idea. :+1:
