### ISSUE TITLE
Difference between this and what's OoB in VS Code

### ISSUE THREAD

**Issue by johnwc** [kondratyev-nv/vscode-python-test-adapter#145]
What is the difference between this test explorer and the one that comes OoB in VS Code?

**Comment by kondratyev-nv** [comment]
@johnwc Thank you for the issue! This is indeed a good question.

The first version of this extension was released in September 2018, about half a year earlier than vscode-python team even started working on the same functionality. Even though I've tried to make them notice my extension and consider cooperation in a couple of comments, I didn't see much of their interest. At that time, my extension already had more than 15K unique installs, so I've decided to continue supporting it. Moreover, at first, their Test View lacked some features and had a lot of bugs, but as you might expect, this changed over another half a year.
 
Now a little on why anyone should consider using this extension over Test View from Python Extension.
 * This extension has better error reporting during the discovery stage. In case of errors, you will see such tests in an errored state, and by clicking on them, a complete error message would be shown in the Output panel.  Python Extension, at best, won't show your tests that contain errors (syntax errors and invalid imports, for example).
 * This extension works better with pytest plugins - Tavern, for example. Python Extension won't discover these tests.
 * This extension is based on [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer). This fact may be useful if you have a workspace with projects in different languages/frameworks. Test Explorer UI has a lot of plugins, and you can conveniently discover and run tests at the same View.
 * This extension will show you errors and a complete output of your tests just by clicking on a failed test.
 * This extension shows only relevant folders from your workspace. Showing all workspace folders, as the Python Extension is doing, can be an issue when you have multiple workspace folders, but only a couple of them have any tests.
 * There might be some configurations when this extension will discover and run your tests, but Python Extension - won't.
 * User experience with both extensions is highly subjective. However, you might like the user interface of this extension better. Also, each discovery, test execution, and test cancellation won't require you to select a folder when you have multiple in your workspace.
 
Python Extension still is excellent, and it is a must-have extension for Python coding in VSCode. This is why, from the beginning, I decided to use the same configuration properties as they used for testing. The same properties help users to configure their test discovery only once. And as long as your tests are discovered and executed, and you're happy using your Test View, that's great even if you're not using my extension. But for any of the reasons listed above or just out of curiosity, please, try Python Test Explorer for Visual Studio Code. If you have any issues or feature requests - [file an issue](https://github.com/kondratyev-nv/vscode-python-test-adapter/issues). If you're happy using it - star this repo and [share your positive feedback in VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter&ssr=false#review-details).
 
I guess it would be better to copy that to the README file.
