### ISSUE TITLE
Missing CHANGELOG.md

### ISSUE THREAD

**Issue by CodeTroopers** [kondratyev-nv/vscode-python-test-adapter#147]
Could you add a CHANGELOG.md file for that we can see difference between version?

**Comment by kondratyev-nv** [comment]
@CodeTroopers Thank you for the issue! Yeah, no problem, I will add CHANGELOG.md. In the meantime, you can see changes between versions on Releases page https://github.com/kondratyev-nv/vscode-python-test-adapter/releases.

**Comment by kondratyev-nv** [comment]
@CodeTroopers I've just published a new version 0.4.2 with the CHANGELOG.md.
