### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by MHKamel** [kondratyev-nv/vscode-python-test-adapter#148]
- Issue Type: `Bug`
- Extension Name: `vscode-python-test-adapter`
- Extension Version: `0.4.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by kondratyev-nv** [comment]
@MHKamel Thank you for the issue! Unfortunately, I don't see any information to understand what is wrong. Can you please describe what is not working for you? Also, additional information about what Python and what test framework you're using would be of help.
