### ISSUE TITLE
Panel hides when test passed successfully

### ISSUE THREAD

**Issue by mishagin-tim** [kondratyev-nv/vscode-python-test-adapter#161]
It's very annoying when you need a terminal window but it closes when your test passed successfully. **How to prevent that?**

P.S. I know that you can just rerun your test cases while your 'output' tab is closed (for example, 'terminal' is opened). But it's very inconvenient when you doing TDD and and you need to monitor your progress step by step. I don't want to switch tabs every time i need to run my tests (**only for holding the panel opened!! It's just stupid!**).

![Kapture 2020-06-21 at 14 48 44](https://user-images.githubusercontent.com/16304454/85223967-8c335d00-b3cf-11ea-8453-be59af459a5e.gif)

**Comment by kondratyev-nv** [comment]
@mishagin-tim Thank you for the issue! Have you found a solution to your problem? Just in case, this is [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) default behavior, and it can be configured with `testExplorer.hideEmptyLog` setting. Setting it to `false` should help.

**Comment by mishagin-tim** [comment]
> @mishagin-tim Thank you for the issue! Have you found a solution to your problem? Just in case, this is [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) default behavior, and it can be configured with `testExplorer.hideEmptyLog` setting. Setting it to `false` should help.

Yes, I've found... Just drag your 'output' tab into the 'terminal' tab and it will be devided into two. But this solution has unintended consequences... Yours is better. Thank you for your feedback! Hope you add this case into the docs.
