### ISSUE TITLE
Not marking django unittest as passed

### ISSUE THREAD

**Issue by t-mish** [kondratyev-nv/vscode-python-test-adapter#163]
So, I have checked up this closed issue
https://github.com/kondratyev-nv/vscode-python-test-adapter/issues/21#issue-376186670

And I found that this is the same problem as I have, and it seems that the author created a repository according to the same book which I am learning now (TDD Python 2014, O'Reilly) . So, since there is no pointed out solution for this problem I open (create) this issue again.

**Repository to reproduce the issue:**
https://github.com/mishagin-tim/tdd-django.git

Before running please check out to the branch "issue-test-runner". And be careful, there is a hardcoded path to the geckodriver in the "functional_tests.py". I am planning to run it with a remote driver.

**Comment by kondratyev-nv** [comment]
@mishagin-tim Thank you for the issue! Unfortunately, https://github.com/mishagin-tim/tdd-django.git gives me 404, is that ok? I'll try to look through other Django tutorials to reproduce the issue.

**Comment by kondratyev-nv** [comment]
@mishagin-tim There was an issue not marking unitttest tests as failed if an error occurred during `setUp` or `setUpClass` methods. I've released a version 0.4.4 with a fix. You should see an error now during test execution.

**Comment by kondratyev-nv** [comment]
Using `pytest-django` seems like a good solution to discover and run Django tests with this exension, I've added this to the [README](https://github.com/kondratyev-nv/vscode-python-test-adapter#2-how-to-use-this-extesion-to-run-django-tests). I'm closing this issue.
