### ISSUE TITLE
How to setup test discovery per sub module?

### ISSUE THREAD

**Issue by Chichilele** [kondratyev-nv/vscode-python-test-adapter#166]
So far the only folder structure I found to make it work was a `tests` folder at the root of the project.
```
pkg
    modules
        <...>
    setup.py
    tests
        my_test.py
```
Is there a way to make it work with the following?
```
pkg
    modules
        module1
            tests
                class1_test.py
        module2
                class2_test.py
    setup.py
```
or even like this
```
pkg
    module
        tests
            class1_test.py
    setup.py
```

**Comment by kondratyev-nv** [comment]
@Chichilele Thank you for the issue! There should be no problem with any of these structures. I've tried to discover and run tests from https://github.com/scikit-learn/scikit-learn, which has tests in the root folder and submodules. In both cases, tests were discovered just fine (except for some performance issues on the [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) side, but that's entirely another problem).

What Python version and test framework are you using? Can you run and discover tests from a command line?

**Comment by Chichilele** [comment]
* Python version `Python 3.7.6` 
* Test framework `unittest` 
* Can't discover from the command line

I think I fixed my issue, it was related to the way I set up the tests. The setting wizard "Python: Configure test" doesn't allow one to specify a path such as `module/tests` but setting it in the .vscode/settings.json seems to work fine. Not sure it's an issue or a deliberate choice though. Happy to be told: "you shouldn't be so specific when specifying the folder" :-)

**Comment by kondratyev-nv** [comment]
@Chichilele I'm glad you've resolved your issue. From my experience with unittest the best way is to get things working from the command line first and then copy arguments to settings.json.
I'm closing this issue then. Feel free to comment or create a new issue if you have some problems.
