### ISSUE TITLE
PYTEST_ADDOPTS is not considered in debug configuration (launch.json)

### ISSUE THREAD

**Issue by jamilraichouni** [kondratyev-nv/vscode-python-test-adapter#167]
Visual Studio Code Version: 1.47.0
Python Test Explorer v0.4.4
OS: Darwin x64 19.5.0

When using pytest with pytest-cov coverage module enabled in tox.ini via

```INI
[pytest]
addopts = --cov-report=html
```

it is recommended (see [here](https://code.visualstudio.com/docs/python/testing#_test-configuration-settings)) to have a debug configuration like

```JSON
{
    "name": "Debug Tests",
    "type": "python",
    "request": "test",
    "console": "internalConsole",
    "env": {
        "PYTEST_ADDOPTS": "--no-cov"
    }
}
```
which disables pytest-cov temporary via an according env var `PYTEST_ADDOPTS`.

The test explorer ignores the setting for environment variable PYTEST_ADDOPTS in the debug config from above so that the debugger does not stop at breakpoints when debugging via the button of the test explorer:

![Screenshot 2020-07-10 at 11 05 19](https://user-images.githubusercontent.com/45113557/87137685-998c8a80-c29d-11ea-8fc2-a565000b90b9.png)

In contrast, when clicking the debug icon in the area named "PYTHON" it works and the debugger stops at the defined breakpoint:
![Screenshot 2020-07-10 at 11 08 42](https://user-images.githubusercontent.com/45113557/87138143-4961f800-c29e-11ea-8be5-3831d15a277a.png)

**Comment by kondratyev-nv** [comment]
@jamilraichouni Thank you for the issue! Indeed, launch.json is not taken into account for debug configurations. However, tox.ini is also not considered, so adding any options there should cause any problems. Is that possible that coverage is enabled in pytest.ini or from `python.testing.pytestArgs` setting?

**Comment by jamilraichouni** [comment]
Hi!

`tox.ini` is being read and completely considered when I run tests from the test explorer.
I have no `pytestArgs` defined but a comprehensive config in the `tox.ini` and it produces the test coverage report etc.

My `tox.ini` looks like this:

```INI
[pytest]
addopts =
    --rootdir=.
    -vvv
    --durations=3
    --cov-config=tox.ini
    --cov=jarlib
    --cov=vscode
    --cov-report=html
    --cov-report=term
    -n6
testpaths = tests
norecursedirs = .git docs/build
python_files = test_*.py
python_classes = *Suite
python_functions = test*
markers =
    log: Marks tests for the module jarlib.log
usefixtures =
    set_pytest_env_var

; coverage:
[run]
branch = True
omit = */conda_env/*,*/tests/*,*/__init__.py,*/__main__.py

[report]
exclude_lines =
    pragma: no cover
    sys\.path\.insert.*
    .*?if __name__.*?__main__.*

[html]
directory = reports/test_coverage

[isort]
py_version=auto
sections=FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
import_heading_stdlib=Standard library:
import_heading_thirdparty=3rd party:
import_heading_firstparty=1st party:
import_heading_localfolder=local:
known_third_party=arrow,click,flask,flask_cors,flask_restplus,flask_sqlalchemy,json5,lxml,matplotlib,numpy,pandas,plotly,psutil,pytest,requests,scipy,scrapy,selenium,sphinx,waitress,xlrd,xlwt
known_first_party=doorsapi,jarlib,vscode
; according to black formatting:
multi_line_output=3
include_trailing_comma=True
force_grid_wrap=0
use_parentheses=True
ensure_newline_before_comments=True
line_length=88
```

My `Coder/User/settings.json` contains:

```JSON
{
    "python.testing.pytestEnabled": true,
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestPath": "/Users/user/repos/jar/conda_env/bin/pytest",
    "pythonTestExplorer.testFramework": "pytest"
}
```

**Comment by kondratyev-nv** [comment]
Yeah, it looks like pytest indeed takes its options from tox.ini. Sorry, I did not know that and was not able to reproduce because I had both tox.ini and pytest.ini files. I will take a look at how to take into account the debug config. In the meantime, I can suggest adding PYTEST_ADDOPTS to a `.env` file or temporarily comment `--cov` arguments.

**Comment by kondratyev-nv** [comment]
@jamilraichouni I've just published a new version 0.4.5 with loading debug options from launch.json. At this point the following debug options are loaded:

- env
- stopOnEntry
- showReturnValue
- redirectOutput
- debugStdLib
- justMyCode
- subProcess

The extension will look for a launch.json configuration with `"type": "python"` and `"request": "test"` to load any of those options. Please, update and let me know if the issue persists.

**Comment by jamilraichouni** [comment]
Hi, thanks!

I've not tested everything but I can at least confirm, that `"env"` and `"stopOnEntry"` are being considered and the debugger also stops at the defined breakpoint although there is a pytest-cov config in the `tox.ini` file.

Hence, this issue can be closed but as said, I've not tested all the changed in v0.4.5.

Have a good day!

**Comment by kondratyev-nv** [comment]
Glad to hear that it helped!
