### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pauelm** [kondratyev-nv/vscode-python-test-adapter#170]
- Issue Type: `Performance`
- Extension Name: `vscode-python-test-adapter`
- Extension Version: `0.4.5`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.47.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\admin\littlefoxteam.vscode-python-test-adapter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kondratyev-nv** [comment]
@pauelm Thank you for the issue! Can you please attach C:\Users\admin\littlefoxteam.vscode-python-test-adapter-unresponsive.cpuprofile.txt file to the issue? Also, can you provide additional information? Like what test framework are you using? How many tests do you have? How long does it take for your tests to be discovered/completed without extension (for example, from command line)?
