### ISSUE TITLE
python.pythonPath is being deprecated. This change breaks test-explorer

### ISSUE THREAD

**Issue by dfioravanti** [kondratyev-nv/vscode-python-test-adapter#177]
Microsoft announced that they will slowly deprecate python.pythonPath in https://devblogs.microsoft.com/python/python-in-visual-studio-code-may-2020-release/ and specifically the section "Coming Next: moving python.pythonPath out of settings.json". The rational behind it is explained in microsoft/vscode-python#2125

For work we need this feature so I manually activate it and it breaks test-explorer. Right now test-explorer defaults to the standard python environment when I run or debug the tests.

In vscode-restructuredtext/vscode-restructuredtext/issues/222 is it possible to see how another extension that depended on python.pythonPath fixed the problem.

**Comment by kondratyev-nv** [comment]
@dfioravanti Thank you for the issue and detailed explanation! I will take a look.

**Comment by dfioravanti** [comment]
Your are welcome. Thanks a lot for the great extension 😊

**Comment by kondratyev-nv** [comment]
@dfioravanti I've just published a new version 0.6.0 that includes getting `pythonPath` setting value from the Python extension. Please, update and let me know how it works for you and whether you have any issues with that change.

**Comment by dfioravanti** [comment]
Sorry, I have been busy at work and I forgot to reply. Looks good to me. Thanks a lot for the change and for the amazing piece of software =)
