### ISSUE TITLE
TestCase not show in Python Test Explorer and CodeLens adornments If one of pytest testcases got error during testcase discorver process

### ISSUE THREAD

**Issue by SilenceHe** [kondratyev-nv/vscode-python-test-adapter#179]
For Example, I have 1000 pytest testcases in my project, but only one of them got error (like code defect, or logic issues, and so on...) cause testcase discorvery failed, For now, looks all testcases will not shown in **Python Test Explorer** List, and **CodeLens adornments** also not appeared within my testcase code, So It's hard for me to run or debug a normal (not the error testcase), I have to use other debuger tools like ipdb to debug my code. In this case, can we show the normal testcase and just exclude the error(s) in Python Test Explorer List? It's really hard for me if one case failures cause all testcases collect failed.

**screenshots:**
![Snipaste_2020-08-23_12-07-01](https://user-images.githubusercontent.com/4414171/90970595-a0afe500-e539-11ea-97f1-5ac739975eb2.png)

**Comment by kondratyev-nv** [comment]
@SilenceHe Thank you for the issue. It looks like you're using Test Explorer from the Python Extension and not the Python Test Explorer. In case you're using Python extension to discover and run your tests, please, report the error to them - https://github.com/Microsoft/vscode-python.

However, if you have [Python Test Explorer](https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter) installed it should show any tests with errors to you. It looks like this
<img width="750" alt="image" src="https://user-images.githubusercontent.com/4085884/91193367-b1aa5300-e6ff-11ea-8fee-14c18e4c9ac6.png">

If Python Test Explorer does not show any tests, please, look at messages at Python Test Adapter Log in the Output section. It would be of help if you show the errors from that log and your settings (like python.pythonPath).

**Comment by SilenceHe** [comment]
**Test Explorer UI** and **Python Test Explorer** both installed (looks Python Test Explorer depends on Test Explorer UI), and parts of cases got errors in **Python Test Log** Console, There's nothing shows in Test Explorer List If I'm not fix the errors.

![image](https://user-images.githubusercontent.com/4414171/94334398-35f73b00-000a-11eb-8ed3-0678beb5e4a2.png)

**Comment by SilenceHe** [comment]
Filed another bug for your advice here: https://github.com/microsoft/vscode-python/issues/14116

**Comment by kondratyev-nv** [comment]
@SilenceHe Thank you for clarification. Can you please take a look at messages at `Python Test Adapter Log` in the Output section and send the output here? Also, your showing your configuration from `settings.json` might be of help.

**Comment by SilenceHe** [comment]
Thanks Nikolay Kondratyev, Python Test Adapter Log complains about 'pytest not installed',  It works well after I set python.pythonPath to Python venv path, because pytest was installed in venv.

**Comment by kondratyev-nv** [comment]
@SilenceHe Glad you've resolved it! Just to be sure, does test discovery works for you even when you have tests with errors now?

**Comment by SilenceHe** [comment]
Yes, It works, even some cases got errors.
