### ISSUE TITLE
Test passes in debug, but is shown as still running

### ISSUE THREAD

**Issue by KaravolisL** [kondratyev-nv/vscode-python-test-adapter#180]
I noticed this after adding a new test to my project. The test passes locally when run manually with pytest. It also runs successfully in my CI environment. When I hit debug, the test is shown to pass in the console, but they remain blue in the pane to the left. I've included some screenshots of the problem. 

![image](https://user-images.githubusercontent.com/6414474/90982614-406b7400-e536-11ea-98c3-c0b8e9fd96c7.png)
![image](https://user-images.githubusercontent.com/6414474/90982635-5aa55200-e536-11ea-98db-47f73ae9499f.png)

This new test is unique in that it uses the python module pexpect (wexpect for windows) to spawn a process and interact with it. I'm not sure if this could be causing the problem though.

**Comment by kondratyev-nv** [comment]
@KaravolisL Thank you for the issue! Can you still reproduce it? I've tried couple of options, but I don't even see test to change icon when debugging (thats probably another issue). Also, have you looked at messages in``Python Test Adapter Log` in the Output panel?

**Comment by KaravolisL** [comment]
No longer reproducible
