### ISSUE TITLE
Add onStartupFinished activation event

### ISSUE THREAD

**Issue by lucono** [kondratyev-nv/vscode-python-test-adapter#186]
Consider adding the relatively new [onStartupFinished](https://code.visualstudio.com/api/references/activation-events#onStartupFinished) activation event.

For projects with a very large number of Python tests, the tests take a long time to be fully discovered and displayed by the Python Test Adapter. However, I find that the discovery does not begin until the Test Explorer view is opened, which is usually when I'm about to run a Python test, but then have to wait a long time for the test discovery, which has only then just started.

In my case, this is a mixed JavaScript and Python project, but is detected as a JavaScript project. I will usually spend some time in the JavaScript files before needing to run a Python test.

The vscode team recently added the __*onStartupFinished*__ activation event, which would be a good way to have the Python Test Adapter be able to activate and discover tests ahead of time, but without impacting vscode's startup time, providing an all around better experience for the user who will then most likely have the tests fully discovered and displayed when they eventually switch over to the Test Explorer view to run some tests.

Thanks.

**Comment by lucono** [comment]
@kondratyev-nv, what do you think about adding this? Any potential adverse impact based your past experience with users of the extension? I can close if you believe it to be a potentially undesirable change.

**Comment by kondratyev-nv** [comment]
@lucono Thank you for the issue! I don't see any issues adding it and I'll try experimenting with this.

**Comment by lucono** [comment]
Thank you @kondratyev-nv!

**Comment by kondratyev-nv** [comment]
@lucono I've just published a new version 0.6.0 that includes `onStartupFinished` activation event. Please, update and let me know how it works for you and whether you have any issues with that change.

**Comment by lucono** [comment]
@kondratyev-nv this seems to be working great and as expected. Thanks for the enhancement!
