### ISSUE TITLE
Problems with output panels and conftest.py

### ISSUE THREAD

**Issue by gustavobittencourt** [kondratyev-nv/vscode-python-test-adapter#189]
Dear @kondratyev-nv, this extension is awesome. Thank you very much for this!

I'm facing two issues that I still haven't found a solution:

### 1 - Outputs

I can't see the outputs produced by *Pytest* (neither errors nor print statements) in any of the available output panels. I tried with and without the argument `-s` in `python.testing.pytestArgs`.

![tela - test explorer](https://user-images.githubusercontent.com/7130975/93956392-79128f00-fd28-11ea-807b-3565435dc0be.png)

![tela - python test adapter log](https://user-images.githubusercontent.com/7130975/93956400-7dd74300-fd28-11ea-9e31-4cadf466bbcc.png)

<img width="1792" alt="tela - teste com erro" src="https://user-images.githubusercontent.com/7130975/93956426-90ea1300-fd28-11ea-8027-fc4188f50c21.png">

### 2 - conftest.py

I am using the following `conftest.py` and `pytest.ini` files:

**conftest.py**
```python
# Skip tests marked as 'manual', which exhibits visual outputs and are too slow
import pytest


def pytest_addoption(parser):
    parser.addoption("--manual", action="store_true",
                     help="run tests marked with @pytest.mark.manual)")


def pytest_runtest_setup(item):
    try:
        if 'manual' in item.keywords and not item.config.getoption("--manual"):
            pytest.skip("need --manual option to run this test")
    except ValueError:
        pass

```

**pytest.ini**
```ini
[pytest]

filterwarnings =
    ignore::DeprecationWarning:pyutilib*
    ignore::RuntimeWarning:importlib
    ignore::DeprecationWarning:pyomo*

markers =
    slow: mark a test that takes more than 1 second to run.
    manual: tests with visual outputs that need to be runned manually
```

While the `pytest.skip()` command in `pytest_runtest_setup` is correctly displayed, I'm unable to parse the `--manual` option via `python.testing.pytestArgs` to run my slow tests.

<img width="859" alt="log do --manual" src="https://user-images.githubusercontent.com/7130975/93956498-becf5780-fd28-11ea-9026-de8fa40ac07d.png">

<img width="1792" alt="problema com o --manual" src="https://user-images.githubusercontent.com/7130975/93956537-cf7fcd80-fd28-11ea-81ed-f9c58b7df850.png">

Could you please help me with these issues?

Thank you again and best regards.

**Comment by kondratyev-nv** [comment]
@gustavobittencourt Thank you for the issue! Unfortunately, I can not reproduce the first issue. Without `-s` option in `python.testing.pytestArgs` I can see the output from stdout in the Test Explorer section in the Output panel. After any of your tests fails do you see any output when clicking on a failed test (`test_second` from your screenshot, there should be at lease error on assert)?

I'll try to reproduce the second one in the meantime.

**Comment by gustavobittencourt** [comment]
@kondratyev-nv I didn't notice the `Show Log` option above each individual test (I thought it was automatic). When I clicked on it, the test output was correctly shown in the output panel. Thank you so much!
Do you know if it's possible to highlight the output panel log syntax like it is highlighted when I hover the mouse over the test? 

![image](https://user-images.githubusercontent.com/7130975/96149099-50248a80-0edf-11eb-9e48-f326fb4e454c.png)

About the second issue, with the `--manual` option I configured through `conftest.py`, I still didn't find a solution.

**Comment by kondratyev-nv** [comment]
@gustavobittencourt 🤔 Test Explorer should show you the log when you click on a test.
![Screen-Recording-2020-10-25-at-1](https://user-images.githubusercontent.com/4085884/97116520-c6f72a00-170e-11eb-8a4a-c9dad6f1ea89.gif)

Regarding the conftest issue. In general running tests from the Test Explorer UI is similar to running pytest from the `python.testing.cwd` folder (workspace folder by default). In your case, it should be `python -m pytest --collect-only -s --manual`. Does running this command from the command line works for you (from the workspace root folder)?

**Comment by gustavobittencourt** [comment]
@kondratyev-nv You just nailed it, my friend!

My `conftest.py` file was in the the project tests subfolder, so Pytest wasn't reading it when called from the root folder.

Thank you so much! You're awesome!

**Comment by kondratyev-nv** [comment]
Glad you've fixed it 🙂 I'm closing this issue then. If something is not working for you or you have other suggestions, please feel free to create another issue.
