### ISSUE TITLE
Support python.unitTest.pyTestArgs configuration property

### ISSUE THREAD

**Issue by kondratyev-nv** [kondratyev-nv/vscode-python-test-adapter#19]

**Comment by jamescasbon** [comment]
:+1: would like this too 

Think it needs to be added at least here for discovery: 
https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/master/src/pytest/pytestTestRunner.ts#L76

There is a workaround to add PYTEST_ADDOPTS in your .env file

**Comment by hvdklauw** [comment]
Yes please !

Just spend a lot of time trying to figure out why it was taking ages to discover my tests while the python extension run tests button was so much faster :)

For big projects being able to limit (temporarily) which tests it shows and looks for by simply setting the pyTestArgs to a specific folder is a must.

**Comment by daniel-brosche** [comment]
I also need this option to enable debugging of my pytest cases when coverage is configured in the pytest.ini. Debugging only works with disabled coverage `--no-cov`.

**Comment by hvdklauw** [comment]
```
"python.unitTest.pyTestArgs": ["path/to/folder"],
```
I just pass the specific path I want to work with currently :)

I can confirm it works with the 0.3.0 update.

**Comment by kondratyev-nv** [comment]
@hvdklauw Ok, I was just confused because of `--rootdir` argument. Nice to hear that you approach works fine now!

Also, it looks like your problem could be solved with changing `python.unitTest.cwd` to the path you want to work with.

**Comment by hvdklauw** [comment]
That actually doesn't work in all cases because of the way pytest discovers
it's dependencies.

**Comment by JarekParal** [comment]
@kondratyev-nv I would like to ask you. I wanted to set `-m` parameter for pyTest marks with logical operator `not` but it doesn't work for me. 

Do I miss something or is there a problem with the extension?

```json
    "python.testing.pytestArgs": [
        "tests",
        "-m \"not my_mark\""
    ],
``` 
With this setting I still see all tests.

But without `not` and quotation marks work everything well:

```json
    "python.testing.pytestArgs": [
        "tests",
        "-m my_mark"
    ],
``` 
in `Test Explorer` are just tests which are marked as `my_mark`

**Comment by kondratyev-nv** [comment]
@JarekParal I think it should be 
```
"python.testing.pytestArgs": [
        "tests",
        "-m",
        "not my_mark"
    ],
```

At least it looks like it worked for on my simplified sample tests.

**Comment by kondratyev-nv** [comment]
Also 
```
"python.testing.pytestArgs": [
        "tests",
        "-m not my_mark"
    ],
```
works. I think this is even might be preffered, since it also works with the Test Explorer from the Python extension.

**Comment by JarekParal** [comment]
Thanks, I did not realize this way because in console `pytest -m not my_mark` doesn't work (on Windows). It returned `ERROR: file not found: my_mark`
