### ISSUE TITLE
Packages specified in PYTHONPATH not found after upgrade to 0.5.0

### ISSUE THREAD

**Issue by hmoravec** [kondratyev-nv/vscode-python-test-adapter#190]
I have a package and its path is specified in `PYTHONPATH`, e.g. `PYTHONPATH=<other paths>:/path/to/my-package`. The tests are found correctly using version 0.4.6 but fail to load using version 0.5.0 with `ModuleNotFoundError: No module named '<my-package>'`.

**Comment by kondratyev-nv** [comment]
@hmoravec Thank you for the issue! Can you please provide a little more information on this. Ideally, a small reproducable example. Also, please, share what Python version you're using, what are your settings and what testing framework you're using to run your tests.

**Comment by hmoravec** [comment]
Please see this minimal example: 
[tests-bug.zip](https://github.com/kondratyev-nv/vscode-python-test-adapter/files/5288204/tests-bug.zip)

The tests run correctly using version 0.4.6 but fails with `ModuleNotFoundError` using version 0.5.0.

**Comment by kondratyev-nv** [comment]
@hmoravec Thank you for the example! Can a problem be caused by devcontainers? I've tried to run tests locally. So without any modifications to the code I can see an error
```
ImportError while importing test module '<path>/tests-bug/test_my_module.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_my_module.py:1: in <module>
    from mypackage.my_module import return_hello
E   ImportError: No module named mypackage.my_module
```
However, I get the same error with running pytest from command line
```
$ pytest .
=================================================================== test session starts ====================================================================
platform darwin -- Python 3.7.7, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/nik/Downloads/tests-bug
plugins: describe-1.0.0
collected 0 items / 1 error                                                                                                                                

========================================================================== ERRORS ==========================================================================
____________________________________________________________ ERROR collecting test_my_module.py ____________________________________________________________
ImportError while importing test module '<path>/tests-bug/test_my_module.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_my_module.py:1: in <module>
    from mypackage.my_module import return_hello
E   ModuleNotFoundError: No module named 'mypackage'
================================================================= short test summary info ==================================================================
ERROR test_my_module.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================== 1 error in 0.13s =====================================================================
```
But when I add `.env` file to modify PYTHONPATH
```
PYTHONPATH=mypackages:$PYTHONPATH
```
test discovery and execution works fine. I'm using Python 3.7.7 and pytest 6.0.1.

I'll try to reproduce the issue using devcontainers.

**Comment by hmoravec** [comment]
I put `PYTHONPATH` to `.env` file in the workspace root and it works now. However in version 0.4.6 (and in tests in Python extension and in plain pytest) it works even when the `PYTHONPATH` is specified only system-wide (in the container).

**Comment by kondratyev-nv** [comment]
Is suppose this can be caused by https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/master/src/pytest/pytestTestRunner.ts#L155, but I don't see how. Unfortuately, I still haven't configured devcontainers to reproduce it.
