### ISSUE TITLE
Re-run tests on save

### ISSUE THREAD

**Issue by afernando79** [kondratyev-nv/vscode-python-test-adapter#193]
Unless I have simply missed the documentation, I wondered if this extension can be configured to trigger a rerun of all (only failed) tests upon changes being detected in files being watched?

I am interested as I would like to develop in an "always green" manner without the need to actively click "Run All Tests" button in the side-bar.

**Comment by kondratyev-nv** [comment]
@afernando79 Thank you for the issue! Unfortunately, the extension does not watch any files at the time.

**Comment by afernando79** [comment]
Thanks for your speedy response @kondratyev-nv . Just curious, but is this something that is possible but not yet implemented or is it simply impossible to make the tests re-run automatically upon save?

**Comment by afernando79** [comment]
Looking at another recent (#192 ) you added an activationEvent of onStartupFinished. Is it possible that extension can be triggered to run all tests upon saving? So is there a "onCommand:vscode.save(all)" for example that can be used to re-trigger the extension? Also, if this were to be possible, can the tests actually be re-run or will the extension simply refresh the list of tests listed?

Sorry lots of questions but am quite keen to get this to work as it makes TDD much easier in VSC. I can help with this feature if needed but have limited JS coding experience.

**Comment by kondratyev-nv** [comment]
@afernando79 I don't see any particular reason why it can be impossible now. But I have not had a look into it. 
In general, I see it similar to https://github.com/kondratyev-nv/vscode-python-test-adapter/issues/137. The extension will need to track what test files are opened. And when something changes in them, run test discovery again (and possibly execute them as in your case).
I'm not sure whether it would be possible for discovery to work correctly for a single file (or a couple of files). But it is more of a performance concern.

Regarding activation events, I'm not sure if it can be used in such scenario. I thought this is a set of events on when to activate (start) the extension, so I think it's one time thing.

**Comment by afernando79** [comment]
Thanks for your thorough and quick response again! If what you describe is a possibility when configured to do so - only re-run them if "automatically re-run on detected changes", I think that would add a significant benefit. If so I am sure the dev team I work within would quite possible adopt it.

If you need anything from me, testing etc, let me know and I can see what I can do to help out.
Thanks again.

**Comment by kondratyev-nv** [comment]
@afernando79 I've just published a new version 0.6.0 that supports test auto-detection and auto-run on save. To enable autorun, right-click on a test suite and select "Enable autorun". After that, any changes to files in a workspace will re-execute tests when files are saved. See the example below.
![Screen-Recording-2020-10-06-at-2](https://user-images.githubusercontent.com/4085884/95249072-d9bdc380-0820-11eb-89ab-57d147bce6ac.gif)

You can enable autorun for all tests by clicking on three dots in the Test explorer UI bar.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/4085884/95249184-007bfa00-0821-11eb-813a-20a24719fb74.png">
 
Please, update and let me know how it works for you and whether you have any issues.

**Comment by afernando79** [comment]
Hi,

That’s amazing! I have checked it out and so far (albeit with only a short poke) everything is working perfectly! Excellent work 😊

I will let my team know also but this is a great feature! Thanks for taking the time to implement it.

Kindest regards

Andy

**Comment by kondratyev-nv** [comment]
Glad to hear it works! I’m closing this issue then. If something is not working for you or you have other suggestions, please feel free to create an issue.
