### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Chibuikem709** [kondratyev-nv/vscode-python-test-adapter#199]
- Issue Type: `Performance`
- Extension Name: `vscode-python-test-adapter`
- Extension Version: `0.6.1`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.50.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/75/myldl7l52hzffpmvmy2f798r0000gn/T/littlefoxteam.vscode-python-test-adapter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kondratyev-nv** [comment]
@Chibuikem709 Thank you for the issue! Can you please attach /var/folders/75/myldl7l52hzffpmvmy2f798r0000gn/T/littlefoxteam.vscode-python-test-adapter-unresponsive.cpuprofile.txt file to the issue? Also, can you provide additional information? Like what test framework are you using? How many tests do you have? How long does it take for your tests to be discovered/completed without extension (for example, from command line)?
