### ISSUE TITLE
Make it easier to contribute

### ISSUE THREAD

**Issue by yozlet** [kondratyev-nv/vscode-python-test-adapter#20]
Tonight I was keen to contribute some fixes to this extension, but I couldn't get it working in my local dev environment before bedtime. Some things that would help:

* Any information in the README about setting it up from source
* Anything to set up the Python environment to run the extension tests
* Separation of unit tests (which could be run in the Mocha Test Explorer) from integration tests (which can only be run using `cross-env` or the debugger, because they require the `vscode` module)

**Comment by kondratyev-nv** [comment]
@yozlet Thank you for the issue!

I have added https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/master/CONTRIBUTING.md. Right now almost all tests are integration tests, so there is no point to separate them at the moment. `cross-env` and additional `vscode` modules are installed locally. However, the system dependencies to run tests are python and python3. I consider using something like Docker to have tests that are easier to run from scratch. Another way would be to use single python command for the tests. However, this case will require additional steps to run tests for various configurations.

**Comment by yozlet** [comment]
@kondratyev-nv Thank you for the rapid response, and the `CONTRIBUTING.md`!

At present I'm only running the extension tests from within VSCode, and they always fail on the `python3` tests: `spawn python3 ENOENT` every time. I'm on a Mac, and I've tried various combinations of virtualenvs along with the system & homebrew pythons, but no luck yet. I'm going to keep poking and see what I can work out.

**Comment by darkvertex** [comment]
Have you thought about just configuring a free CI solution? Then you don't need to rely on people to run the tests in advance, it can just happen when they make the PR of their contribution.

A lot of people seem to like [Travis](https://travis-ci.com) for Linux unittest builds. Here's an example config with multiple Python versions:
https://github.com/pyblish/pyblish-base/blob/master/.travis.yml
and for Windows test builds it seems almost everyone uses [AppVeyor](https://appveyor.com). Here's an example config:
https://github.com/pyblish/pyblish-base/blob/master/appveyor.yml

**Comment by kondratyev-nv** [comment]
@darkvertex Travis CI is already configured for this repository, see https://travis-ci.com/kondratyev-nv/vscode-python-test-adapter/ and https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/master/.travis.yml. And of course, I do not rely only on local test runs. 

@yozlet If you have troubles setting your environment and are ok with opening PR you can do it and see how tests will run in CI.

However, configuring and supporting environment for the tests is a pain, and I consider other solutions, maybe #25 will be of help.

**Comment by yozlet** [comment]
I'm a big fan of plugging external CI into GitHub, and I agree that this project could use it. (Personally, I like CircleCI best.) I don't think it's a great replacement for running tests locally, because the code-test-fix cycle takes so much longer with it. However, it's a lot better than nothing, and in my case (tests are mostly running except for environment-specific ones), it would probably get me moving. Thanks for the suggestion!
