### ISSUE TITLE
La extensión provoca una alta carga de CPU

### ISSUE THREAD

**Issue by Ghostdroid1** [kondratyev-nv/vscode-python-test-adapter#203]
- Issue Type: `Performance`
- Extension Name: `vscode-python-test-adapter`
- Extension Version: `0.6.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\andyg\AppData\Local\Temp\littlefoxteam.vscode-python-test-adapter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kondratyev-nv** [comment]
@Ghostdroid1 Thank you for the issue! Can you please attach c:\Users\andyg\AppData\Local\Temp\littlefoxteam.vscode-python-test-adapter-unresponsive.cpuprofile.txt file to the issue? Also, can you provide additional information? Like what test framework are you using? How many tests do you have? How long does it take for your tests to be discovered/completed without extension (for example, from command line)?
