### ISSUE TITLE
Workspace/launch settings not being used

### ISSUE THREAD

**Issue by tom-randell** [kondratyev-nv/vscode-python-test-adapter#204]
Hi there I am struggling to get the launch settings picked up - really I just want to add the:

```json
"env": {
          "MONGODB_URI": "localhost:27017",
          "DATABASE_NAME": "test"
        }
```

but its not working - I tried seeing if adding the envFile property would do anything but it doesn't seem to either.
Atm I have the following configuration in my workspace file (have also tried this with just having a launch.json and same result):

```json
{
        "name": "PyTest",
        "type": "python",
        "request": "test",
        "console": "integratedTerminal",
        "justMyCode": false,
        "envFile": "${workspaceFolder}/foooooo/.env",
        "env": {
          "MONGODB_URI": "localhost:27017",
          "DATABASE_NAME": "test"
        }
      }
```

But in the python test adapter log it just keeps saying:

Reading configuration for workspace emitwise-flask
usingNewInterpreterStorage feature flag is 'true'
...
Loading environment variables file ${workspaceFolder}/.env

I have followed the instructions here https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter and even literally just done:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug test",
      "type": "python",
      "request": "test",
      "console": "externalTerminal",
      "justMyCode": false,
      "stopOnEntry": true,
      "envFile": "${workspaceFolder}/fooooooo/.env"
    }
  ]
}
```

But always just seems to get ignored - any ideas?

My workspace settings:

```json
"settings": {
    "editor.formatOnSave": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "python.analysis.typeCheckingMode": "off",
    "python.formatting.provider": "black",
    "python.languageServer": "Pylance",
    "python.linting.mypyArgs": [],
    "python.linting.mypyEnabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.pylintUseMinimalCheckers": false,
    "python.testing.pytestEnabled": true,
    "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
  },
```

**Comment by tom-randell** [comment]
An update to this - it seems that the environment variables ARE being passed in but are being overwritten by the .env file - and having looked around the code it looks like the only place looking for a .env file is in the python-test-adapter logs - not sure if there is something in this extension that automatically looks for a .env and if there is a way to stop it doing that? or make sure that the options set by the launch options override those settings

**Comment by tom-randell** [comment]
Another quick update - it looks like it's only checking the local launch.json as opposed to workspace files even though at a quick glance in the code you are looking for workspace files - I think the detectDebugConfiguration function should also work with workspace files

**Comment by kondratyev-nv** [comment]
@tom-randell Thank you for the issue! Do you have a multi-root workspace and a debug configuration in `.code-workspace` file? If that is the case, yeah, I don't think these are considered right now. Otherwise, the extension is loading environment variables in the following order.
1. VSCode process variables (System by default)
2. `envFile` file if it exists (`${workspaceFolder}/.env` by default)
3. `env` setting from launch.json file.

**Comment by tom-randell** [comment]
Closing this issue as it seems to be an issue with VsCode and Mac or some specific version of this combination as opposed to being a problem specific to this extension
