### ISSUE TITLE
[enhancement] Show stderr in "Output" panel

### ISSUE THREAD

**Issue by trallnag** [kondratyev-nv/vscode-python-test-adapter#205]
Atm the output in Output panel only includes captured logs and captured std out. But in my case (using Loguru instead of default Python logging) all the logging goes to stderr and is not captured by Pytest. And this means that I'm unable to the stderr / logs when I run tests with the adapter.

**Comment by kondratyev-nv** [comment]
@trallnag I've just published a new version 0.6.3 that will display captured stderr in the Output panel. Please, update and let me know how it works.

**Comment by trallnag** [comment]
Hey @kondratyev-nv, I came around to test it and it works great. Thanks a lot. Now I don't have to try to make Pytest capture logs from Loguru
