### ISSUE TITLE
Not marking django unittest as passed

### ISSUE THREAD

**Issue by davidfilat** [kondratyev-nv/vscode-python-test-adapter#21]
Whenever I run the test from the Test Explorer UI, the functional tests using selenium are run and marked as passed, but the Django unittests are not marked as test. The extensions is set to use pytest.
<img width="220" alt="screen shot 2018-11-01 at 00 33 22" src="https://user-images.githubusercontent.com/1475163/47822812-316a6f00-dd6e-11e8-8804-06e5e3824617.png">

When I run the tests from Terminal using pytest, all tests are passed.
<img width="704" alt="screen shot 2018-11-01 at 00 34 10" src="https://user-images.githubusercontent.com/1475163/47822813-32030580-dd6e-11e8-8cc9-e907db359950.png">

**Comment by kondratyev-nv** [comment]
@davidfilat Thank you for the issue! Can you please provide a sample test to reproduce it?

**Comment by davidfilat** [comment]
The entire repository is available here: https://github.com/davidfilat/superlists

**Comment by kondratyev-nv** [comment]
@davidfilat Do you still have this issue? I've tried to run tests in some sample Django project and it looks ok right now. And it looks like your repository was removed, so I can't check your tests.

**Comment by davidfilat** [comment]
It has been fixed. Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
