### ISSUE TITLE
option to generate junit xml

### ISSUE THREAD

**Issue by orellabac** [kondratyev-nv/vscode-python-test-adapter#211]
Is it possible to have an option to save an results.xml ?

I love this extension and I would like to be able to run my tests from the extension but still get a results.xml that I can use for generating other reports.

**Comment by kondratyev-nv** [comment]
@orellabac Thank you for the issue! It's possible and was implemented in version 0.4.6 (issue #172,  https://github.com/kondratyev-nv/vscode-python-test-adapter/issues/172#issuecomment-683274745). Just add `--junitxml=results.xml` to the `python.testing.pytestArg` setting. However, notice that a report will be generated using `xunit1` format.

**Comment by orellabac** [comment]
Excellent!!! I am so happy now!. Thanks!
