### ISSUE TITLE
When extension is active, creating a new terminal automatically pastes and runs a venv Activate.ps1 script

### ISSUE THREAD

**Issue by darthwalsh** [kondratyev-nv/vscode-python-test-adapter#212]
How can I turn off the `.../venv/bin/Activate.ps1` text getting pasted into my terminal, that seems to come from this extension?

Without Python Test Explorer for Visual Studio Code active, if I exit my terminal session and create a new integrated terminal session (using my shell `/usr/local/bin/pwsh`), then a new terminal loads, as expected.

When I enable Python Test Explorer for Visual Studio Code, exit the terminal, then create a new terminal, then a split second after the terminal loads the text `& /Users/walshca/adsk/ansible-automations/venv/bin/Activate.ps1` appears inside my terminal and is run. Then if I deactivate Python Test Explorer for Visual Studio Code and reload, when I create a new terminal, nothing appears as expected.

Ditto if I change my shell to zsh: with the extension active `source /Users/walshca/adsk/ansible-automations/venv/bin/activate` appears and is run.

This windows has a completely different folder open: `~/OneDrive/bin`! Though, I do have a different VS Code instance open at `~/adsk/ansible-automations`, maybe some wires are getting crossed. I have these extensions installed:
```
littlefoxteam.vscode-python-test-adapter
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
```

but when I have the other three active and only Python Test Explorer disabled I don't get the unexpected `.../venv/bin/Activate.ps1` appearing. Maybe the source of the automatic activate isn't Python Test Explorer, but it's strange that this only happens when this extension is active.

**Comment by kondratyev-nv** [comment]
@darthwalsh Thank you for the issue! Unfortunately, Python Test Explorer does not implement any such behavior. As I know it's a feature of the Python extension when there is a virtual env configured. To make sure, can you please try to uninstall Python Test Explorer, install only the Python extension, and see whether the activation script is called for the same workspace folder?

**Comment by darthwalsh** [comment]
Agreed, I think this behavior comes from `python.pythonPath` from another extension. Thanks for considering!
