### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by YoussefAbdouni** [kondratyev-nv/vscode-python-test-adapter#215]
- Issue Type: `Bug`
- Extension Name: `vscode-python-test-adapter`
- Extension Version: `0.6.3`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by kondratyev-nv** [comment]
@YoussefAbdouni  Thank you for the issue! Can you please paste additional information of the issue here? Also, can you provide additional information? Like what test framework are you using? When you saw any issues (screenshot might be helpful)?
