### ISSUE TITLE
Broken if you have variables in your configured Python/Pytest executable path

### ISSUE THREAD

**Issue by darkvertex** [kondratyev-nv/vscode-python-test-adapter#22]
I have a multi-root workspace and each root has a `settings.json` which looks like:

```
{
    "python.pythonPath": "${workspaceFolder}/.rez-python.sh",
    "python.unitTest.pyTestPath": "${workspaceFolder}/.rez-pytest.sh",
    "python.linting.pylintPath": "${workspaceFolder}/.rez-pylint.sh",
    "python.linting.pylintUseMinimalCheckers": false
}
```
I do this because of the setup at work, we use Rez:
https://github.com/nerdvegas/rez
to manage our environments, so I made some utility scripts which put me in the correct Python environment (via Rez) for that tool, be it python itself or pytest or pylint.

When I have such a configuration, in the `Test Explorer` Output log, if I try to run a test, I got:
```
Error occurred during process execution: Error: spawn ${workspaceFolder}/.rez-python.sh ENOENT
```
Normally ENOENT = no such directory, so perhaps it's just a matter of the "${variables}" not being resolved prior to spawning?

For reference, VSCode supports variables in its settings:
https://code.visualstudio.com/docs/editor/variables-reference

**Comment by kondratyev-nv** [comment]
@darkvertex Thank you for this issue! I'll have a look. You're probably right that #19 can affect this, but #19 is about `python.unitTest.pyTestPath` which is not used right now.
