### ISSUE TITLE
Process exited with code 4: ERROR: not found (no name

### ISSUE THREAD

**Issue by JackPott** [kondratyev-nv/vscode-python-test-adapter#220]
Spent all day trying to debug this and can't narrow it down, I'm more inclined to think its a configuration thing than a "bug" but I'm reaching out for help as its driving me bonkers.  I'm in VS Code using Python Test Explorer, this is a FastAPI app. 

The suite run fine from the terminal with `python3 -m pytest` but the explorer shows all errors. I have added a single test to one of my files which asserts 1==1, running that on its own from Test Explorer and looking at the log yields:
```
2021-12-25T15:56:26.539Z  DBG pytest at 'myproject': usingNewInterpreterStorage feature flag is 'true'
2020-12-25T15:56:26.539Z INFO pytest at 'myproject': Using auto-detected pythonPath /home/linuxbrew/.linuxbrew/opt/python@3.7/bin/python3
2020-12-25T15:56:26.539Z INFO pytest at 'myproject': Running tests using python path '/home/linuxbrew/.linuxbrew/opt/python@3.7/bin/python3' in /home/username/dev/myproject
2020-12-25T15:56:26.540Z INFO pytest at 'myproject': Loading environment variables file /home/username/dev/myproject/.env
2020-12-25T15:56:26.544Z INFO pytest at 'myproject': Running pytest with arguments: --rootdir=/home/username/dev/myproject, --junitxml=/tmp/tmp-7162-SPrxasFlnTse, --override-ini, junit_logging=all, --override-ini, junit_family=xunit1, /home/username/dev/myproject/server/src/tests/test_accounts.py::::test_one_equals_one
2020-12-25T15:56:26.545Z INFO pytest at 'myproject': Running pytest as a Python module
2020-12-25T15:56:27.526Z CRIT pytest at 'myproject': Execution of the test "/home/username/dev/myproject/server/src/tests/test_accounts.py::::test_one_equals_one" failed: Process exited with code 4: ERROR: not found: /home/username/dev/myproject/server/src/tests/test_accounts.py::::test_one_equals_one
(no name '/home/username/dev/myproject/server/src/tests/test_accounts.py::::test_one_equals_one' in any of [<Module test_accounts.py>])
```

The weird bit in there for me is the `::::`, if I try and run `python3 -m pytest server/src/tests/test_accounts.py::::test_one_equals_one` it fails the same way, but works with two colons per usual pytest syntax.

If I go to debug that test I get much the same

```
============================= test session starts ==============================
platform linux -- Python 3.7.8, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/username/dev/myproject
plugins: bdd-3.4.0, metadata-1.11.0, forked-1.1.3, sugar-0.9.3, xdist-1.32.0, html-3.0.0, pspec-0.0.4
collected 0 items
==DISCOVERED TESTS BEGIN==
{"tests": [], "errors": []}
==DISCOVERED TESTS END==

============================ no tests ran in 1.01s =============================
ERROR: not found: /home/username/dev/myproject/server/src/tests/test_accounts.py::::test_one_equals_one
(no name '/home/username/dev/myproject/server/src/tests/test_accounts.py::::test_one_equals_one' in any of [<Module test_accounts.py>])
```

I tried running tests from the native test panel. That doesnt doesn't discover any tests at all (as it none come up in the list), but the run button does actually find them and execute them- but leaves its own colourful trail of errors behind it. _I am aware this is a pretty damning clue that this is not specific to test-adapter, but I wasn't aware that the two modules shared any logic, just some config declarations_

```
INTERNALERROR>   File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/username/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 107, in pytest_collection_finish
INTERNALERROR>     test, parents = self.parse_item(item)
INTERNALERROR>   File "/home/username/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 77, in parse_item
INTERNALERROR>     return parse_item(item)
INTERNALERROR>   File "/home/username/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/testing_tools/adapter/pytest/_pytest_item.py", line 176, in parse_item
INTERNALERROR>     parameterized=parameterized,
INTERNALERROR> NotImplementedError: Unexpected pytest node (see printed output).

========================= 24 tests collected in 0.40s ==========================

The Python extension has run into an unexpected situation
while processing a pytest node during test discovery.  Please

nodeid: server/src/tests/test_accounts.py::::test_can_create_account
kind: ('function', False)
class: Function
name: test_can_create_account
fspath: /home/username/dev/myproject/server/src/tests/test_accounts.py
location: ('server/src/tests/test_accounts.py', 10, 'test_can_create_account')
function: <function test_can_create_account at 0x7f45155d2b90>

...snip...

  File "/home/username/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 44, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 3)

============================= test session starts ==============================
platform linux -- Python 3.7.8, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/username/dev/myproject
plugins: bdd-3.4.0, metadata-1.11.0, forked-1.1.3, sugar-0.9.3, xdist-1.32.0, html-3.0.0, pspec-0.0.4
collected 24 items

server/src/tests/test_accounts.py .....                                  [ 20%]
server/src/tests/test_messages.py ..........x........                    [100%]

-------------- generated xml file: /tmp/tmp-7162Xiy4mBHLNQZm.xml ---------------
======================== 23 passed, 1 xfailed in 1.12s =========================
```
 
Similar :::: thing. I have observed that the native test panel will collect if I remove __init__.py from my tests directory, but that causes me some relative import issues. Exploring this thread further I have tried my tests in several spots. 
They are currently adjacent to the app (/app and /tests, with __init__.py's all over), but I've tried them in app/tests as well as next to app/main.py (ie app/test_accounts.py)

Appreciate it if this rings any bells for anyone and they can offer any pointers.

**Comment by kondratyev-nv** [comment]
@JackPott Thank you for the issue! I was going to ask you a lot of questions, but then I noticed that you have a couple of plugins installed. It seems that `pspec` is messing up pytest node ids 😢 I think I'll take a look at whether it is possible to integrate the Python Test Explorer with this plugin.

Meanwhile, I would suggest disabling it for the test explorer. You can disable it with adding `"-p", "no:pspec"` to the "python.testing.pytestArgs" setting. Unfortunately, right now it won't help to run your tests with the Python Test Explorer (I'll investigate why), but it should be ok to run with the stock Python extension. Otherwise, you can disable it by adding `
addopts = -p no:pspec` to the `pytest.ini` file (see https://docs.pytest.org/en/latest/plugins.html#deactivating-unregistering-a-plugin-by-name), this way it will work with both extensions.

**Comment by JackPott** [comment]
Hey @kondratyev-nv great spot, thank you thats exactly the problem. Didn't realise pspec was quite so invasive. I uninstalled it and Test Explorer is back in action exactly as one would expect. Appreciate the PR you dropped to pspec too so it can just be disabled in the future. They aren't super active over there so I hope it gets accepted. Thanks again, Merry Christmas!
