### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by liaskowski** [kondratyev-nv/vscode-python-test-adapter#221]
- Issue Type: `Bug`
- Extension Name: `vscode-python-test-adapter`
- Extension Version: `0.6.5`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 14264,
		"activateCallTime": 42,
		"activateResolvedTime": 4,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "littlefoxteam.vscode-python-test-adapter",
				"_lower": "littlefoxteam.vscode-python-test-adapter"
			},
			"activationEvent": "onStartupFinished"
		}
	},
	"runtimeErrors": []
}
```

**Comment by kondratyev-nv** [comment]
@liaskowski Thank you for the issue! Can you please paste additional information on the issue here? Also, can you provide additional information? Like what test framework are you using? When did you see any issues (a screenshot might be helpful)?
