### ISSUE TITLE
UI bug: Bad grouping of tests resulting in two main root containers for the same repo

### ISSUE THREAD

**Issue by darkvertex** [kondratyev-nv/vscode-python-test-adapter#23]
I had this repo open as non-primary root in a multi-root workspace: https://github.com/pyblish/pyblish-qml/
...and in the Test Explorer the UI looks like this:
![image](https://user-images.githubusercontent.com/941331/47857943-47ede600-ddc1-11e8-9e8a-a6f3ee9ffa98.png)

See how there's 2 of `pyblish-qml - All tests`? yet their contents are not really duplicated.

One seems to have filenames (with unittest class names under them, and then methods under those) and the other is names of classes in test files (with methods under them.)

**Comment by darkvertex** [comment]
From my user settings:
```
    "pythonTestExplorer.testFramework": "unittest",
```
The other keys are not set, so defaults. As for the workspace settings, nothing there and nothing relevant in the folder settings for this particular folder.

**Comment by kondratyev-nv** [comment]
Well, this looks strange. I thought #26 would fix it, but maybe there something more to it. Still, let's see how #29 will affect your issue. I will add a comment here after release will be published.

**Comment by darkvertex** [comment]
#29? I don't see a link. Did you type that number right?

**Comment by kondratyev-nv** [comment]
@darkvertex Yeah, you're right its PR #26

**Comment by kondratyev-nv** [comment]
@darkvertex I have published release 0.2.1. Please, update the extension and let me know if the issue persists.

**Comment by darkvertex** [comment]
Seems to be fixed. No more doubled groups at the root.
