### ISSUE TITLE
pytest: collect and run doctests

### ISSUE THREAD

**Issue by yozlet** [kondratyev-nv/vscode-python-test-adapter#24]
When `pytest` is run with the `--doctest-modules` option, it'll collect doctests like so:

```xml
<Package '/Users/yoz/Code/MyPeeps/core'>
  <DoctestModule 'models.py'>
    <DoctestItem 'core.models.Person.instance_type.__str__'>
    <DoctestItem 'core.models.Person.instance_type.display_name'>
    <DoctestItem 'core.models.Person.instance_type.next_anniversary'>
    <DoctestItem 'core.models.Person.instance_type.split_name'>
...
```

**Comment by kondratyev-nv** [comment]
@yozlet The support for `python.unitTest.pyTestArgs` was added in version 0.3.0. So now doctests are discovered when `--doctest-modules` argument is present in the `python.unitTest.pyTestArgs` property. Please, update the extension and let me know if you have any questions/suggestions/problems.

**Comment by yozlet** [comment]
@kondratyev-nv Worked immediately on update, no tweaks needed. YOU WIN, SIR!
