### ISSUE TITLE
Duplicated Code Lens with Python extension

### ISSUE THREAD

**Issue by kingsimba** [kondratyev-nv/vscode-python-test-adapter#243]
![image](https://user-images.githubusercontent.com/8407634/117526468-ec3aee00-aff7-11eb-9327-a5b9901e2c2c.png)

Is there any document tells how to fix this?

**Comment by jspreddy** [comment]
This needs to be supported by vscode. They seem to be discussing a config option here:
https://github.com/microsoft/vscode-python/issues/10898#issuecomment-771877111

**Comment by kondratyev-nv** [comment]
@kingsimba @jspreddy Thank you for the issue. Unfortunately, this is because one set of Code Lenses is provided by the Python extension and another one is by Python Test Explorer. If you use only Python Test Explorer to run your tests, you can disable testing functionality by the Python extension with the following settings
```
{
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": false,
    "pythonTestExplorer.testFramework": "pytest" // (or unittest)
}
```

Let me know if this helps.

Related to #129.

**Comment by kingsimba** [comment]
It helped! Thanks.

> @kingsimba @jspreddy Thank you for the issue. Unfortunately, this is because one set of Code Lenses is provided by the Python extension and another one is by Python Test Explorer. If you use only Python Test Explorer to run your tests, you can disable testing functionality by the Python extension with the following settings
> 
> ```
> {
>     "python.testing.unittestEnabled": false,
>     "python.testing.nosetestsEnabled": false,
>     "python.testing.pytestEnabled": false,
>     "pythonTestExplorer.testFramework": "pytest" // (or unittest)
> }
> ```
> 
> Let me know if this helps.
> 
> Related to #129.

**Comment by dandiep** [comment]
I would recommend putting this on the main extension page - it took me some digging to find this, and it is very confusing for a newbie (like myself) to have the two Run code lens buttons.

**Comment by kondratyev-nv** [comment]
@dandiep I've added the solution to the [README](https://github.com/kondratyev-nv/vscode-python-test-adapter#1-disable-duplicated-code-lenses).
