### ISSUE TITLE
Error in test_

### ISSUE THREAD

**Issue by Ch1lled** [kondratyev-nv/vscode-python-test-adapter#248]
I have several files with test for one api. One of the tests returns json. When I try to use it as a variable in tests from other files Test Explorer shows that there is an "Error in test_%testname%.py" and there are no Run | Debug | ... buttons in this tests. 
![изображение_2021-05-26_180830](https://user-images.githubusercontent.com/58484496/119684695-60292300-be4d-11eb-91fd-93a861ea74c0.png)

**Comment by kondratyev-nv** [comment]
@Ch1lled Thank you for the issue! `Error in <test file name>` usually means there are some errors in this file detected on the test discovery stage (invalid syntax, import of missing module, etc). You can click on that test and you should see an actual error in Output panel.

**Comment by Ch1lled** [comment]
> @Ch1lled Thank you for the issue! `Error in <test file name>` usually means there are some errors in this file detected on the test discovery stage (invalid syntax, import of missing module, etc). You can click on that test and you should see an actual error in Output panel.

If I don't use json from new_user test it's alright and if I click on "Debug this test" there are no issues with both "broken" tests while running. But thanks, I'll try to find something wrong with my code.

**Comment by kondratyev-nv** [comment]
I can assume that there is something wrong with importing a method or this "variable from other file". Do you see an actual error in the Output panel?
Additionally, you can try verifying your code by doing test discovery/execution from the command line. 
Anyway, feel free to reopen the issue if you find out any new details.

**Comment by kondratyev-nv** [comment]
Can you post the error here? It'd be easier to identify the issue that way. Have you tried running test_api_lk_login from the command line?

**Comment by Ch1lled** [comment]
test_api_lk_login.py:14: in <module>
    user = new_user.test_new_user()
test_api_lk_new_user.py:24: in test_new_user
    assert response_body['status'] == 1
E   assert 0 == 1

If I run the login test using pytest .\test_api_lk_login.py it's is ok.

**Comment by kondratyev-nv** [comment]
I see. This happens because you're using `new_user.test_new_user()` in the global scope, which is executed during the test discovery stage. And assert is triggered as there is probably some setup (or mocking) missing at that stage. Consider wrapping this in some kind of function and call this function in tests. Let me know if this helps.

**Comment by Ch1lled** [comment]
Made a separate user creation function and with its import it finally works, thanks a lot.
