### ISSUE TITLE
Use https://tox.readthedocs.io/en/latest/ (Tox) for testing different flavours of python so windows users can run integration tests and find it easier to contribute

### ISSUE THREAD

**Issue by jakegt1** [kondratyev-nv/vscode-python-test-adapter#25]
As said above. This should also allow for testing of more versions of python (3.4, 3.5, 3.6 etc) if wanted in the future.

**Comment by kondratyev-nv** [comment]
Thank you for the issue! I will take a look at Tox. I hope this will also help with #20!

**Comment by kondratyev-nv** [comment]
@jakegt1 The extension is now configured to be able to run tests with Tox! See https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/6517979db89cfac36d388c20667d205fc7b4db30/tox.ini. I have successfully run tests with Tox on multiple local setups and in some cases in CI (see https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/6517979db89cfac36d388c20667d205fc7b4db30/.travis.yml and https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/6517979db89cfac36d388c20667d205fc7b4db30/.azure-pipelines.yml#L94). So I think this issue can be closed. If you have any other suggestions or problems feel free to create a new issue or PR!
