### ISSUE TITLE
how to make the tests run on each change?

### ISSUE THREAD

**Issue by siraj-samsudeen** [kondratyev-nv/vscode-python-test-adapter#260]
I read in one of the review's posted on the extension marketplace that it supports the functionality to rerun tests upon saving of a file. Is there any setting that needs to be configured to enable this?

**Comment by kondratyev-nv** [comment]
@siraj-samsudeen Thank you for the issue! To enable autorun, right-click on a test suite and select "Enable autorun". After that, any changes to files in a workspace will re-execute tests when files are saved. See the example below.
![Screen-Recording-2020-10-06-at-2](https://user-images.githubusercontent.com/4085884/95249072-d9bdc380-0820-11eb-89ab-57d147bce6ac.gif)

You can enable autorun for all tests by clicking on three dots in the Test explorer UI bar.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/4085884/95249184-007bfa00-0821-11eb-813a-20a24719fb74.png">
 
Let me know if it works for you.

**Comment by siraj-samsudeen** [comment]
@kondratyev-nv Thank you SOOOO much for taking the time to capture a screenshot and make it perfectly clear how this works. I have configured it and it works so wonderfully well to the point that I am rethinking whether I should even stop pytest-watch from running all the tests in the background as I can selectively auto-run the tests using this beautiful add-in. 

To help newbies like me, have you considered creating a video tutorial or something of that sort so that we can easily get all the benefits of a wonderful addin like this? 

I have another issue as well - when I click on Run Test, it runs the test in Python 
![image](https://user-images.githubusercontent.com/11910293/125023515-ac968e00-e09c-11eb-961a-b14cef9468f5.png)

And I keep seeing Python in the Test bar - is there way to disable the default Python testing and enable only the Test Explorer? 
![image](https://user-images.githubusercontent.com/11910293/125023584-cf28a700-e09c-11eb-8e79-5bbbf51494ce.png)

**Comment by kondratyev-nv** [comment]
@siraj-samsudeen I've tried to describe the benefits of this extension in the README. Recently, I've added the solution to the common questions there - https://github.com/kondratyev-nv/vscode-python-test-adapter#faq.

You can remove duplicated Code Lenses and disable testing with the Python extension by updating configuration, see https://github.com/kondratyev-nv/vscode-python-test-adapter#1-disable-duplicated-code-lenses.

**Comment by siraj-samsudeen** [comment]
@kondratyev-nv thanks a lot for the response. I have the exact 4 lines in my settings file. However, I see both code lenses from Python extension as well as the test-tree from Python in the Testing sidebar. So, what does disabling Testing by Python extension supposed to achieve. Sorry if this was obvious to you. But it is not.

**Comment by kondratyev-nv** [comment]
@siraj-samsudeen Well, it should work... I've tried it right now and unfortunately, it does not take effect until restart. Have you tried to restart VSCode?

**Comment by siraj-samsudeen** [comment]
Yes I did and it has worked. Thank you so much. It has been such a pleasure
to have a prompt response from you on every question I ask.

Is there an option to run only the last-failed-test that is available in
pytest?

**Comment by kondratyev-nv** [comment]
@siraj-samsudeen Sorry for the late reply. Unfortunately, at the moment no. Right now, pytest arguments for last-failed (and similar options) are filtered out as they break test discovery.
