### ISSUE TITLE
.env variables are not loaded before executing test

### ISSUE THREAD

**Issue by davidfilat** [kondratyev-nv/vscode-python-test-adapter#27]
I have prepared my Django project for deployment on Heroku and most of the settings are set using environment variables. Since I've made this change the Test Explorer shows all the tests as failed, however, if I run the tests manually from the VS Code editor window (the small run button above test definition), they run properly and all of them pass.

Therefore I've deducted that the Test Explorer UI doesn't load the environmental variables used by VS Code from .env. I hope you manage to fix this issue!

Thank you!
Here is my .env file:

`DJANGO_SETTINGS_MODULE=superlists.settings`
`DJANGO_SECRET_KEY='*************'`
`SITENAME='127.0.0.1'`
`DATABASE_URL='postgres://********/***'`

**Comment by kondratyev-nv** [comment]
@davidfilat I have published release 0.2.4. Please, update the extension and let me know if the issue persists.

**Comment by davidfilat** [comment]
It seems to be working! Thank you very much!
