### ISSUE TITLE
launch.json reports that '"request": "test",' is invalid, wants "attach" instead.

### ISSUE THREAD

**Issue by MarximusMaximus** [kondratyev-nv/vscode-python-test-adapter#280]
When adding 
```
        {
            "name": "Python: Debug Test (PythonTestExplorer)",
            "type": "python",
            "request": "test",
            "justMyCode": false,
        }
```
to launch.json, VSCode complains that `"test"` is an invalid valid for `"request"`. It wants to use `"attach"` instead. Please support checking for either string, so as to be backwards compatible (test) but also to stop VSCode from complaining (attach).

![Screen Shot 2022-04-07 at 15 36 30](https://user-images.githubusercontent.com/94208961/162330728-8568795b-df36-4f82-87be-3c07aa594787.png)

Thank you.

**Comment by kondratyev-nv** [comment]
@MarximusMaximus I've added support for '"purpose": ["debug-test"]' and any 'request' to detect a valid debug configuration. Please, update to version 0.7.1 and let me know if this works for you.

**Comment by MarximusMaximus** [comment]
Seems to work. Thank you!
