### ISSUE TITLE
error discovering pytets

### ISSUE THREAD

**Issue by guobq** [kondratyev-nv/vscode-python-test-adapter#287]
![image](https://user-images.githubusercontent.com/42168217/188269192-12359e3c-01c5-4aad-a5dd-2b75fc1f7539.png)
The use case can be run normally  by pytest 
but  error discovering pytest tests  hint in TEST EXPLORER  filter

**Comment by kondratyev-nv** [comment]
Thank you for the issue! Unfortunately, these errors are from [Python extension for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-python.python) and shouldn't affect the work of Python Test Explorer for Visual Studio Code (this extension). You can report it to the other extension.
