### ISSUE TITLE
v0.8.0 consumes 360 MB (37k files!) against v0.7.1 with 2 MB (300 files)

### ISSUE THREAD

**Issue by Diogo-Rossi** [kondratyev-nv/vscode-python-test-adapter#301]
The new version v0.8.0 consumes 360 MB (37k files!) against v0.7.1 with 2 MB (300 files).

Is that ok? I'm using 2 machines with different versions and just found that.

![image](https://github.com/kondratyev-nv/vscode-python-test-adapter/assets/57204023/ba7bdcf7-2f42-4a6d-a78d-6eb13d9c34a5)

![image](https://github.com/kondratyev-nv/vscode-python-test-adapter/assets/57204023/1188d6a1-9719-4257-b172-90afcd97e155)

**Comment by kondratyev-nv** [comment]
Thank you for the issue! This is not ok, I’ll publish the fixed version in the next 24h.

**Comment by Diogo-Rossi** [comment]
The folder of the previous version does not get deleted when I update and close/open VSCode (or reload).

I've noted this happens with other extensions too, some o then very old.

Can I delete these folders without problem?

**Comment by kondratyev-nv** [comment]
Well, I'm not an expert on how VSCode stores/caches extensions, but I don’t see why not 🙂 The extension is self contained and doesn’t store anything in the extension folder.
