### ISSUE TITLE
Test Explorer installed by not using Test Explorer UI? No option to rerun on save

### ISSUE THREAD

**Issue by JustAHobbyDev** [kondratyev-nv/vscode-python-test-adapter#315]
I had installed the extension and it was initially working. I had 2 separate 'Test Explorer' panels, one with the native ui and one with the Test Explorer Ui where I could selected rerun on save.

I don't know what I did, but now the Test Explorer Ui doesn't show up.

<img width="905" alt="testexploer-issue" src="https://github.com/user-attachments/assets/97057cdc-d4f2-45f1-bbc6-cee7e4f5f01a">

Any idea what the problem might be?

**Comment by segfly** [comment]
@JustAHobbyDev: In your `settings.json` add the following:
```
"testExplorer.useNativeTesting": false
```

It seems this is set to true by default on a fresh install - which as a new user to this tool was very confusing to me when all the docs and screenshots show the "autorun" feature which appears to be missing in the native UI.

It's a shame there is no other way (at least I can find) to enable the auto-run feature while using the native UI. I find the code lens actions distracting, but it's the only way to easily run/debug tests from the editor. Unlike with the native UI, where the gutter has extra menu items to run/debug tests. 🤷

**Comment by JustAHobbyDev** [comment]
@segfly - Thanks, I was able to get it working with this.
