### ISSUE TITLE
VSCode shows duplicate tests in Python

### ISSUE THREAD

**Issue by semihsezer** [kondratyev-nv/vscode-python-test-adapter#316]
Type: <b>Bug</b>

I don't know if this due to a recent update, but I am seeing my Python tests appear twice and when I am in test debug mode it runs twice as well. How can I fix this? I just created an empty project and I am running into the same issue.

I have 4 debuggers appearing for python, I tried setting it to only one and I am still running into the same issue.

Please see this stackoverflow question I posted for better formatting: 
https://stackoverflow.com/questions/79063876/vscode-shows-duplicate-tests-in-python

Steps to reproduce:
1. `python -m venv .venv` (create virtualenv)
1. `source ./.venv/bin/activate` (activate virtualenv)
1. `pip install pytest==8.3.3`
1. On VSCode select Python interpreter to be the virtualenv one.
1. `mkdir server server/tests`
1. Basic tests file
    ```python
    # server/tests/test_storage.py
    import pytest

    class TestStorage:
        def test(self):
            pass
    ```

7. Settings.json (I tried different variations with the directory)
    ```json
    {
      "python.testing.pytestArgs": [
        "tests"
      ],
      "python.testing.unittestEnabled": false,
      "python.testing.pytestEnabled": true
    }
    ```

<img width="369" alt="Screenshot 2024-10-08 at 12 07 06 AM" src="https://github.com/user-attachments/assets/6e79c2c4-e3b7-484c-8112-952ea055ae72">
<img width="349" alt="Screenshot 2024-10-08 at 12 06 44 AM" src="https://github.com/user-attachments/assets/10cc294d-0695-4128-8c34-aff82223cd3c">
<img width="332" alt="Screenshot 2024-10-08 at 11 03 34 AM" src="https://github.com/user-attachments/assets/e1f1ec87-2869-4118-ba6d-bfce9b2b854e">

Many thanks in advance!

Extension version: 0.8.2
VS Code version: Code 1.94.0 (Universal) (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 94c29571-b8b3-4004-a2c4-48e6c903f304|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31150323
notype1:31151523
showbadge:31153266
5fd0e150:31146321

```

</details>

**Comment by kondratyev-nv** [comment]
@semihsezer Thank you for the issue! Test functionality is provided by two extensions - [Python ](https://marketplace.visualstudio.com/items?itemName=ms-python.python) and [Python Test Explorer for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter). This is why you see 2 sets of tests - the first one is being provided by this extension, the second is by Python extension. While reproducing this looks the same:
![image](https://github.com/user-attachments/assets/e40f3114-d427-4d6d-9391-ff0d12ac8c06)

**Comment by semihsezer** [comment]
@kondratyev-nv thanks for your response! I turned off the second extension and everything is good now!
