### ISSUE TITLE
Locale variables not defined

### ISSUE THREAD

**Issue by matejcik** [kondratyev-nv/vscode-python-test-adapter#37]
Test adapter seems to run with empty environment. That makes some sense, but it's arguably incorrect wrt locales.

Namely, Python 3 < 3.7 assumes US-ASCII locale if none is defined, which is wrong in most cases. E.g., [Click](https://click.palletsprojects.com/en/7.x/) refuses to work with this locale.

Test adapter should either pass through `LANG` and `LC_*` from the environment, or alternately set a reasonable default (e.g., `C.UTF-8` on systems that support it)

**Comment by kondratyev-nv** [comment]
@matejcik Thank you for the issue! Indeed, this is a bug, and I am going to fix it in #27. Just in case I might be not aware of something, why do you think running tests with an empty environment makes any sense?

**Comment by matejcik** [comment]
well someone could argue that tests _should_ run in an empty environment, in order to make them more deterministic / less reliant on your local config. I assumed that the empty env is a deliberate choice for roughly this reason. (but then there should be the option to configure the environment, which is what #27 is about, presumably)

Personally I would prefer to inherit the full environment normally, that makes it easier to e.g. configure pytest through env vars. Test runners such as tox should take care of the determinism. But I can see arguments for either choice.

**Comment by kondratyev-nv** [comment]
@matejcik I have published release 0.2.4. Please, update the extension and let me know if the issue persists.

**Comment by kondratyev-nv** [comment]
I'm closing this issue because this feature was released and it looks like there are no problems with that right now. If someone has any issues feel free to create a new one!
