### ISSUE TITLE
test case not discovered when files are under a folder

### ISSUE THREAD

**Issue by ShaneCarr** [kondratyev-nv/vscode-python-test-adapter#38]
under vs code i have the following
masterfolder
      /dev
      /test

if i put the code under dev and test the test cases are not discovered, if i place them under master folder it works fine. Is that by design or is this an environmental problem.

**Comment by kondratyev-nv** [comment]
@ShaneCarr Thank you for the issue! Have you configured the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) to discover and run your tests? Also, what test framework are you using and how does it work when you are running your tests from the command line?

**Comment by kondratyev-nv** [comment]
I'm closing this issue because there is not enough information about this specific case. And in general, it looks like there are no problems with that right now. If someone has any issues feel free to create a new one!
