### ISSUE TITLE
UI: Add path differentiation for identical file names

### ISSUE THREAD

**Issue by yozlet** [kondratyev-nv/vscode-python-test-adapter#40]
I'm working on a project which has multiple folders below the project root, and each folder has its own `tests.py`. So my Test Explorer looks like this:
![image](https://user-images.githubusercontent.com/173848/50177182-2b950280-02b6-11e9-845c-cd5246e6ab02.png)
... which is not hugely helpful when trying to find the right one.

When dealing with multiple identically-named files, VSCode's practice is to differentiate on path by adding a smaller path description to tab headers:
![image](https://user-images.githubusercontent.com/173848/50177413-cee61780-02b6-11e9-83e1-be365be3c287.png)

These smaller, lighter/darker labels (a.k.a. _Descriptions_) are [now available in extension tree views](https://code.visualstudio.com/updates/v1_30#_custom-views). However, that relies on Test Explorer UI implementation ([which I've requested](https://github.com/hbenl/vscode-test-explorer/issues/25)).

In the meantime,  how about changing the label to show a differentiating folder name as well as the file name. So, in a project with these files...

* `foo/stuff/tests.py`
* `bar/tests/tests.py`
* `baz/tests/tests.py`

... the TreeItem labels would be:

* Either `.../stuff/tests.py` or `foo/.../tests.py`
* `bar/.../tests.py`
* `baz/.../tests.py`

**Comment by yozlet** [comment]
On further reading of the VSCode `TreeView` API, it looks like VSCode can handle all that path-differentiation for you _if_ you give it a `resourceURI` to work with. So I'd hold off on this until https://github.com/hbenl/vscode-test-explorer/issues/25 has some kind of resolution.

**Comment by kondratyev-nv** [comment]
@yozlet Thank you for the issue! The additional part of label to distinct test suites was added in version 0.2.7. Please, update the extension and let me know if you have any questions/suggestions/problems.
The distinct part of a path was added in the form of `file.py (unique/path)`. I.e., for your example it should be
* `tests.py (stuff)`
* `tests.py (bar/tests)`
* `tests.py (baz/tests)`

**Comment by yozlet** [comment]
Works great, thank you!
