### ISSUE TITLE
Attempting to cancel test-running throws an error

### ISSUE THREAD

**Issue by iansan5653** [kondratyev-nv/vscode-python-test-adapter#42]
If I am running tests and I attempt to abort using the red "X" button, I get this popup notification:
```
Running the contributed command:'test-explorer.cancel' failed.
```
Nothing appears in the Python Test Adapter Log.

**Comment by kondratyev-nv** [comment]
@iansan5653 Thank you for the issue! The test cancellation feature was added in version 0.2.8. Please, update the extension and let me know if you have any questions/suggestions/problems.
