### ISSUE TITLE
Attempting to debug tests shows an error message and nothing happens

### ISSUE THREAD

**Issue by iansan5653** [kondratyev-nv/vscode-python-test-adapter#43]
Attempting to debug a test (with the debug button on each test) throws an error:
```
Error while debugging test: Error: Method not implemented
```

**Comment by yozlet** [comment]
Which test runner are you using? pytest debugging support was released a few days ago, but I think it's not available for other test runners yet.

**Comment by iansan5653** [comment]
Seems to be working for pytest now, thanks!
