### ISSUE TITLE
Add support for pytest-describe

### ISSUE THREAD

**Issue by pchomik** [kondratyev-nv/vscode-python-test-adapter#45]
Hello,

Thanks for great extension and good work with pytest extension. 
Could you add support for pytest-describe plugin as well?

I did some debugging and I found that tests are put into groups based on file and classes e.g.
```
test_file1 (group) -> Test_Class _1 (group) -> test_method_1
```
I'm not sure how this information is collected by for pytest-describe we have methods inside method. All methods with prefix describe should act like Test Classes and other methods (in my case with prefix it) should act like test methods e.g.
```
test_file_1 (group) -> describe_method_1 (group) -> it_test_method_1
```
In current state all methods with describe prefix are skipped and execution is incorrect because run command look like as follow: ```pytest test_file_1::it_test_method_1``` where it should look like follow ```pytest test_file_1::describe_method_1::it_test_method_1```

It would be great to get support for this plugin because it has native support for all pytest features and organize python tests in the best way (in my opinion).

You can find more about this plugin at page: https://github.com/ropez/pytest-describe
I'm using latest vscode editor and latest version of plugins.

Thank you in advance for help. 
In case of any help I can produce more examples or execute some tests with real code.

Best Regards and Happy new Year
Pawel

**Comment by kondratyev-nv** [comment]
@pchomik Thank you for the issue! The support for pytest-describe plugin was added in version 0.2.5. Please, update the extension and let me know if you have any questions/suggestions/problems.
