### ISSUE TITLE
Capture output from unittest tests

### ISSUE THREAD

**Issue by kondratyev-nv** [kondratyev-nv/vscode-python-test-adapter#5]
Now when running unittest tests only result of a test is captured from a TestResult of failed and skipped tests.
For a debug purpose it would be great to capture stdout from tests.

**Comment by darkvertex** [comment]
When running stuff from `pytest`, the `-s` flag will disable all capturing (silencing) during execution, thus prints and such will make it during execution.

It's quite tricky to know which output is from what test though. The easiest way would be to open the output of the last test run.

**Comment by jamescasbon** [comment]
One possibility is to use the junitxml output which contains all this information in a structured format.

**Comment by yozlet** [comment]
This would also be great for pytest tests. Right now there's only a one-line error, without any further context. This is particularly frustrating given that pytest often gives useful explanations of test failures, but they're not shown.

**Comment by kondratyev-nv** [comment]
@yozlet JFYI, output capturing for pytest was added in version 0.2.6.

**Comment by yozlet** [comment]
@kondratyev-nv Yep, I noticed. Thank you! With that and fixing test discovery for pytest 4.1.x, you've removed the two blockers that were keeping me on the command line.
