### ISSUE TITLE
pythonPath not working properly if it contains ..

### ISSUE THREAD

**Issue by mattpepin** [kondratyev-nv/vscode-python-test-adapter#52]
My pythonPath is: ${workspaceRoot}/../bin/python
It has to be relative to fix an issue regarding the debugger, and everything else is working properly. However, when discovering tests, I get:

```
2019-01-17T00:25:30.775Z info at 'src' [unittest runner]: Discovering tests using python path "/home/matt/Projects/test/src/bin/python" in /home/matt/Projects/test/src with pattern *test*.py and start directory .
2019-01-17T00:25:30.801Z crit at 'src' [unittest runner]: Test loading failed: Error occurred during process execution: Error: spawn /home/matt/Projects/test/src/bin/python ENOENT
```

The .. is ignored. The path should be /home/matt/Projects/test/bin/python

**Comment by kondratyev-nv** [comment]
@mattpepin Thank you for the issue! This behaviour looks strange, do you mind providing some additional information?

Currently `${workspaceRoot}` placeholder is not replaced or considered in any way (probably it should be, so I created a new issue #53). But a placeholder is not replaced when it is not recognised, so it should look like this in the log
```
2019-01-17T07:30:57.912Z info at 'pytest-sample' [pytest runner]: Discovering tests using python path "/home/kondratyev-nv/pytest-sample/${workspaceRoot}/.tox/py36-pytest41/bin/python" in /home/kondratyev-nv/pytest-sample
```
Are you sure that you have `pythonPath` set to `${workspaceRoot}/../bin/python` and do not override it somewhere?

Can you tell me, what is the value of `pythonPath` in the Python Extension? You can see it in the Python section in the Output tab. Something like
```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.72.0
Initializing for /home/kondratyev-nv/pytest-sample/.tox/py36-pytest35/bin/python
```

**Comment by mattpepin** [comment]
My pythonPath is set in settings.json in the workspace like this:

`"python.pythonPath": "${workspaceRoot}/../bin/python"`

I don't have the same output that you have. Here's the output:
`Starting Jedi Python language engine.`

I'm on Arch Linux by the way.

**Comment by kondratyev-nv** [comment]
@mattpepin You're right, somehow there is no such output from Python Extension when setting `python.jediEnabled` is set to `true`.

Does Python Extension successfully discover and run your tests?

**Comment by mattpepin** [comment]
No, but it does if I change pythonPath to remove the .. or if I create a symlink src/bin. In the first case, I lose the debugger (because of a bug in VSCode). In the second, it pollutes my source tree a little.

I disabled jedi temporarily (not even sure what it is). Here's what I get:

```
Microsoft Python Language Server version 0.1.75.0
Initializing for /home/matt/Projects/test/src/../bin/python
```

**Comment by kondratyev-nv** [comment]
@mattpepin Can you share a link to the bug in VSCode?

So, am I right, that when you remove `..` from the pythonPath the tests are discovered by both the Python Extension and in the Test Explorer?

And just to be sure, when I'm talking about Python Extension test discovery I mean discovering/running them with the button in the bottom of the window.
![image](https://user-images.githubusercontent.com/4085884/51330559-d43aab80-1a88-11e9-8ac8-d4a5c5e23abf.png)

**Comment by mattpepin** [comment]
No, if I remove the .., I can't run my project anymore and I get a prompt to install pylint and to choose a python interpreter. However, if I click the reload arrow in the tests panel, some tests are picked up. I don't see the Run Tests in the bottom bar like your screenshot, with or without the ...

![screenshot from 2019-01-17 13-27-42](https://user-images.githubusercontent.com/582959/51340148-2fa27480-1a5c-11e9-902e-34bd73bffd05.png)

![screenshot from 2019-01-17 13-28-11](https://user-images.githubusercontent.com/582959/51340167-3204ce80-1a5c-11e9-863e-b5490ffe86df.png)

The VSCode bug affects the debugger:
https://github.com/Microsoft/vscode-python/issues/2865

**Comment by mattpepin** [comment]
I also have the following venvPath: "${workspaceFolder}/../.." if it matters.

**Comment by kondratyev-nv** [comment]
@mattpepin Sorry for asking a lot of questions. I reproduced it and can confirm the bug. The #51 should fix it.

**Comment by mattpepin** [comment]
You're right, workspaceFolder works for both (tests and app). It seems workspaceRoot it deprecated so it's a win-win situation. Thanks!

**Comment by kondratyev-nv** [comment]
`workspaceRoot` placeholder support was added in version 0.2.7.
