### ISSUE TITLE
Cannot debug unittest

### ISSUE THREAD

**Issue by kalahl** [kondratyev-nv/vscode-python-test-adapter#57]
When I try to debug a test using unittest I get
"Error while debugging test: Error: Unittest debugging is not supported at the time."

Do you have any plans for releasing debugging with unittest?

Workaround is to use pytest.

**Comment by kondratyev-nv** [comment]
@kalahl Thank you for the issue! I have plans on implementing it, but no specific dates or milestones. As a workaround, you should be able to debug tests with Python Extension and CodeLens.

So, from test explorer you can go to a test case and start debugging it with "Debug Test" CodeLens.
![image](https://user-images.githubusercontent.com/4085884/51835261-eed51600-230d-11e9-81ac-ff00a2aecc0d.png)

**Comment by kondratyev-nv** [comment]
Debugging for unittest was added in version 0.4.1.
