### ISSUE TITLE
Support python.unitTest.pyTestPath configuration property

### ISSUE THREAD

**Issue by kondratyev-nv** [kondratyev-nv/vscode-python-test-adapter#60]

**Comment by lucono** [comment]
It would be great to have this feature. One big challenge from the lack of support for the option (which has since been renamed to `python.testing.pytestPath`) is it makes it difficult or impossible to seamlessly integrate with testing setups where `pytest` is a wrapper that performs some additional setup prior to testing.

**Comment by lucono** [comment]
@kondratyev-nv - I've created pull request #182 to contribute this feature.

It's a great extension, and has been incredibly useful to me - Thank you!

**Comment by kondratyev-nv** [comment]
@lucono I've found a case with a virtual environment when `pytest` is not recognized as a command. 
1. Remove any global pytest packages. 
2. Setup virtual environment with `python -m venv .venv`
3. Set `python.pythonPath` to `.venv/bin/python`
4. Try to discover tests in Test Explorer.

I see two possible ways to fix it. First is to modify PATH before running a command (get a base path from `pythonPath` setting and prepend it in PATH). Another one is to do it similarly to how Python Extension does it - https://github.com/DonJayamanne/pythonVSCode/blob/7a58ce8ab29b37393fb0027f151e2a2185477db1/src/client/testing/common/runner.ts#L57 (when value of `pytestPath` is the same as its basename, run it as a module, see https://github.com/DonJayamanne/pythonVSCode/blob/7a58ce8ab29b37393fb0027f151e2a2185477db1/src/client/testing/common/runner.ts#L123).
I'll work on the second option, but if you have any concerns, please, do let me know.

**Comment by lucono** [comment]
@kondratyev-nv Good catch, I can verify the same. I see no concerns with your approach, and can help test the fix when you have it. Thanks!

**Comment by lucono** [comment]
@kondratyev-nv One question - would this approach create any possible scenario where the user has provided a value for `testing.pytestPath`, but that pytest path is not used and `python -m pytest` is used instead?

**Comment by kondratyev-nv** [comment]
@lucono It might be the case when `testing.pytestPath` is set to something like `pytest`, `pytest.sh`, or any other filename-like value. For a case like `pytest.sh` it would be enough to set to a path like `${workspaceFolde}/pytest.sh` to run it as an executable.

**Comment by kondratyev-nv** [comment]
@lucono I've just published a new version 0.5.0 with supporting pytestPath setting. Please, update and let me know if it works for you.

**Comment by lucono** [comment]
@kondratyev-nv Tested it out and it works great. Thank you!
