### ISSUE TITLE
Windows import path for unit-tests

### ISSUE THREAD

**Issue by LeonOnRoad** [kondratyev-nv/vscode-python-test-adapter#64]
Detected an issue regarding a bad formated/joined path for start directory.
This was previously fixed in https://github.com/kondratyev-nv/vscode-python-test-adapter/pull/29
This fix was removed from latest version of the extension (0.3.0), which leads to an error loading tests.

Modifying line 25 in file placeholderAwareWorkspaceConfiguration.js make it work again.
FROM:
this.resolvePath(original.unittestArguments.startDirectory)
TO:
this.resolvePlaceholders(original.unittestArguments.startDirectory)

See bellow the error logs from 'Python Test Log Adapter' and the test folder path which is badly joined.
Adding manually the fix from above fix to the extension installed on my PC made it work ok.

> 2019-02-13T14:07:36.554Z info at 'back-end' [pytest runner]: Reading configuration for workspace back-end
> 2019-02-13T14:07:36.555Z info at 'back-end' [pytest runner]: Pytest test discovery is disabled
> 2019-02-13T14:07:36.873Z info at 'back-end' [unittest runner]: Environment variables file d:\develop\workarea\repos\mycompany\myproject\back-end\.env does not exist
> 2019-02-13T14:07:36.881Z info at 'back-end' [unittest runner]: Discovering tests using python path "d:\develop\workarea\repos\mycompany\myproject\back-end\venv\Scripts\python.exe" in d:\develop\workarea\repos\mycompany\myproject\back-end with pattern *test*.py and start directory d:\develop\workarea\repos\mycompany\myproject\back-end\tests
> 2019-02-13T14:07:37.832Z crit at 'back-end' [unittest runner]: Test loading failed: Process exited with code 1: Traceback (most recent call last):
>   File "<string>", line 90, in <module>
>   File "<string>", line 59, in discover_tests
>   File "C:\Users\myuser\AppData\Local\Programs\Python\Python36\lib\unittest\loader.py", line 338, in discover
>     raise ImportError('Start directory is not importable: %r' % start_dir)
> ImportError: Start directory is not importable: '**d:\\develop\\workarea\repos\\mycompany\\myproject\x08ack-end\tests**'

Errors in the path consists of numerous issues:
d:\\\\develop\\\\workarea\repos\\\\mycompany\\\\myproject\x08ack-end\tests

breaks down to a join between:

- d:\\\\develop\\\\workarea (double backslash)
- \repos (single backslash)
- \\\\mycompany\\\\myproject  (double backslash again)
- \x08ack-end\tests (single backslash again and **\b** being converted to **\x08**)

**Comment by kondratyev-nv** [comment]
@LeonOnRoad Thank you for the issue! Can you tell me what is specified in your configuration? Also, it looks like this is more about escaping is Python script https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/7eacfab4456c13caba1c0da631ce8a3eea200766/src/unittest/unittestScripts.ts#L64

Strings should be treated as raw literals.

**Comment by kondratyev-nv** [comment]
@LeonOnRoad This issue should be fixed in version 0.3.1. Please, update the extension and let me know if the issue persists.

**Comment by LeonOnRoad** [comment]
With version 0.3.1 it works fine. Thanks for fixing this!

I couldn't find '**configuration.startDirectory**' in any of my configuration, settings or launch json files.
Currently my configuration is **Python Current File (Integrated Terminal) (back-end)**

Extract from launch.json (containing the configuration)
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
...
}
```

![image](https://user-images.githubusercontent.com/40380566/52778920-c65c5400-304f-11e9-9460-8af81eeb86ea.png)

**Comment by kondratyev-nv** [comment]
I was talking about the unittest argument `-s` that can be provided in `python.unitTest.unittestArgs` configuration property in the settings.json file. By default `.` (current folder) is used.

**Comment by LeonOnRoad** [comment]
Ok, thanks for clearing that up for me.
Here is my configuration:
```
"python.unitTest.unittestArgs": [
        "-v",
        "-s", "./tests",
        "-p", "*test*.py"
    ]
```
This works fine with the python extension when discovering and running tests.
