### ISSUE TITLE
Tests not discovered by Test Explorer

### ISSUE THREAD

**Issue by SamVanhoutte** [kondratyev-nv/vscode-python-test-adapter#67]
Hello,

I can run my unit tests in visual studio code with the built-in tester (see image):
![image](https://user-images.githubusercontent.com/3539605/53179440-fb3e4d00-35f3-11e9-816c-8f33848492f0.png)

But when I click the refresh button on the Test Explorer view, I get the following exception in the Python Test Adapter output:
Especially the "Error: spawn python ENOENT" is unclear to me.  Any idea on what I need to change?

> 2019-02-21T15:13:43.723Z info at 'python-musings' [unittest runner]: Reading configuration for workspace python-musings
> 2019-02-21T15:13:43.727Z info at 'python-musings' [pytest runner]: Reading configuration for workspace python-musings
> 2019-02-21T15:13:43.727Z info at 'python-musings' [pytest runner]: Pytest test discovery is disabled
> 2019-02-21T15:13:43.728Z info at 'python-musings' [unittest runner]: Environment variables file d:\github\python-musings\.env does not exist
> 2019-02-21T15:13:43.730Z info at 'python-musings' [unittest runner]: Discovering tests using python path "python" in d:\github\python-musings with pattern test*.py and start directory d:\github\python-musings\src\01-regular-expressions
> 2019-02-21T15:13:43.736Z crit at 'python-musings' [unittest runner]: Test loading failed: Error occurred during process execution: Error: spawn python ENOENT

Below, you can see the settings.json file: 

```json
{
    "python.unitTest.unittestArgs": [
        "-v",
        "-s",
        "./src/01-regular-expressions",
        "-p",
        "test*.py"
    ],
    "python.unitTest.pyTestEnabled": false,
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.unittestEnabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true
}
```

**Comment by kondratyev-nv** [comment]
@SamVanhoutte Thank you for the issue! What python interpreter should be used? It looks like the global `python` command is used, is that right in your case?

**Comment by SamVanhoutte** [comment]
I guess so.  This is the screenshot of the interpreter selection in vscode:
![image](https://user-images.githubusercontent.com/3539605/53191027-18324a80-360b-11e9-99a7-3af85221a341.png)

**Comment by kondratyev-nv** [comment]
* Do you have this path (`C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64`) in your `PATH` environment variable? 
* Can you try to set `python.pythonPath` to this path (`C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python.exe`)?
* Does running `python` from the command line work fine?

**Comment by caiwan** [comment]
I have the same issue, but it gives a complete different error log:

```
TypeError: Cannot read property 'on' of undefined
    at complete.tslib_1.__awaiter.Promise (//Users/caiwan/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.2.8/src/pythonRunner.ts:54:39)
    at new Promise (<anonymous>)
    at PythonProcessExecution.<anonymous> (/Users/caiwan/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.2.8/src/pythonRunner.ts:51:16)
    at Generator.next (<anonymous>)
    at __awaiter (/Users/caiwan/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.2.8/node_modules/tslib/tslib.js:107:75)
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/caiwan/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.2.8/node_modules/tslib/tslib.js:103:16)
    at PythonProcessExecution.complete (/Users/caiwan/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.2.8/out/src/pythonRunner.js:16:24)
    at UnittestTestRunner.<anonymous> (/Users/caiwan/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.2.8/src/unittest/unittestTestRunner.ts:56:12)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/caiwan/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.2.8/node_modules/tslib/tslib.js:104:62)
```

I have downgraded from version `0.3.1` to version `0.2.8` but didn't seemed to work. Here's my relevant python settings from the current workspace I'm in:

```
{
    "python.pythonPath": "/Volumes/Macos/Users/caiwan/.pyenv/shims",
    "python.unitTest.unittestArgs": [
        "-v",
        "-s",
        "./",
        "-p",
        "test_*.py"
    ],
    "python.unitTest.pyTestEnabled": false,
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.autoTestDiscoverOnSaveEnabled": true,
    "python.jediEnabled": false,
  "python.unitTest.unittestEnabled": true,
  "pythonTestExplorer.testFramework": "unittest",
  "python.unitTest.cwd": "${workspaceFolder}/",
  "python.envFile": "${workspaceFolder}/dev.env",
  "python.linting.flake8Enabled": true,
  "python.linting.enabled": true,
  "python.linting.pylintEnabled": false,
}
```

**Comment by SamVanhoutte** [comment]
> * Do you have this path (`C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64`) in your `PATH` environment variable?
> * Can you try to set `python.pythonPath` to this path (`C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python.exe`)?
> * Does running `python` from the command line work fine?

It seems after a reboot, it worked (don't have a clear idea on what exactly caused this to be fixed, so it's hard to find back the actual root cause now)

**Comment by kondratyev-nv** [comment]
@SamVanhoutte So, everything works fine now, am I right? Since the reboot helped, it looks like there were some problems with the environment variables.

@caiwan Is `/Volumes/Macos/Users/caiwan/.pyenv/shims` a valid Python executable? It looks like it is a path to the folder with the executable. Can you try setting your python.pythonPath to the Python executable itself?

**Comment by SamVanhoutte** [comment]
@kondratyev-nv - thanks, so probably yes.  from my side, the issue can be closed.  thanks for your prompt help !
