### ISSUE TITLE
Test suites that use setUpClass do not work.

### ISSUE THREAD

**Issue by jakegt1** [kondratyev-nv/vscode-python-test-adapter#9]
I haven't collected the exact reasoning for this one, but from what i can tell any unittest.TestCase that uses setUpClass will not run that function. I'm assuming it's because the tests are run outside of their specific suites.

**Comment by jakegt1** [comment]
It's due to how the tests are collected in the python script - as they are given each as their own UnitTest instance, they don't have their attached TestCase suites - so they never run setUpClass.

I've fixed this and will put it up in a fork in a sec..

**Comment by jakegt1** [comment]
Example code:
```python
from unittest import TestCase

class TestStuff():

    @classmethod
    def setUpClass(cls):
        cls.my_data = {"something": "good"}

    def test_something(self):
        assert self.my_data == {"something": "good"}
```

**Comment by kondratyev-nv** [comment]
Closing due to PR #10 merge.
