### ISSUE TITLE
"Process leakage"

### ISSUE THREAD

**Issue by deitry** [kondratyev-nv/vscode-python-test-adapter#94]
Though MS Python extension provides its own discovered tests for TestView, I prefer yours for a couple of reasons. Though it runs smoothely most of time, I found that the more I run tests, the more dangling python3 processes are stay in the system. After a couple of hours it becomes like this and eats all of memory:
![Screenshot_20190816_181706](https://user-images.githubusercontent.com/6714840/63178752-5b69f500-c053-11e9-8aaa-7a929497a451.png)

It doesn't happen if I don't open TestView at all and since testing in MS Python extension is disabled, I suspect this one.

**Comment by kondratyev-nv** [comment]
Thank you for the issue! I will take a look. Are there any specific steps for this to happen or just a long session of work? Maybe you could see if there is some kind of pattern when a process does not shut down.

**Comment by kondratyev-nv** [comment]
@deitry I tried to reproduce this issue for a couple of days but had no luck. I don't see any hanging processes. There are 2 or 3 processes from the extensions that I can see while discovery or test runs, but still, the number of them does not increase over time. I tracked the number with `ps aux | grep python` command. Could you possibly provide an example project to reproduce it? Also output of `ps aux | grep python` would be of help, since the processes started by the extension have a pretty distinctive look.

**Comment by deitry** [comment]
I'm sorry for long delay.
I forgot about `ps -aux` until you pointed it out.
```
user     12994  0.0  0.7 109864 57688 ?        S    15:45   0:01 /usr/bin/python3 -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text <file>
user     13159  0.0  0.4 311644 36852 ?        Sl   15:46   0:00 /usr/bin/python3 -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text <file>
user     13167  0.0  0.7 109872 57636 ?        S    15:46   0:01 /usr/bin/python3 -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text <file>
user     31354  0.0  0.4 311900 37360 ?        Sl   17:44   0:00 /usr/bin/python3 -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text <file>
user     31362  0.0  0.6 103472 51624 ?        S    17:44   0:01 /usr/bin/python3 -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text <file>
user     31416  0.0  0.4 311900 37380 ?        Sl   17:45   0:00 /usr/bin/python3 -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text <file>
user     31424  0.0  0.6 103488 51664 ?        S    17:45   0:00 /usr/bin/python3 -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text <file>
user     32168  0.0  0.4 311900 37412 ?        Sl   17:48   0:00 /usr/bin/python3 -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text <file>
user     32176  0.0  0.6 103488 51748 ?        S    17:48   0:00 /usr/bin/python3 -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text <file>
```
So I guess I found the leaker. Another sorry about suspecting your extension.
