### ISSUE TITLE
Tests are discovering but not running

### ISSUE THREAD

**Issue by Kenuat** [kondratyev-nv/vscode-python-test-adapter#97]
Hi, I'm trying to start using Tavern (https://taverntesting.github.io/) over pytest framework. I got my tests discovered in the explorer, but when I try to run it, it instantly stops. 
Log show only the following:

> 2019-08-29T12:21:03.913Z info at 'tools' [pytest runner]: Reading configuration for workspace tools
> 2019-08-29T12:21:03.914Z info at 'tools' [pytest runner]: Running tests using python path 'C:\Users\user\AppData\Local\Programs\Python\Python37\python.exe' in c:\Users\user\repos\tools
> 2019-08-29T12:21:03.915Z info at 'tools' [pytest runner]: Environment variables file c:\Users\user\repos\tools\.env does not exist
> 2019-08-29T12:21:06.881Z info at 'tools' [pytest runner]: Test execution completed

The test still displayed as it wasn't run and I get no test logs output.
How to investigate this problem further? Everything works fine using the terminal (I'm running on Windows via Powershell).

Thanks in advance.

**Comment by kondratyev-nv** [comment]
@Kenuat Thank you for the issue! I can reproduce the problem with an example from Tavern Quickstart documentation. I will try to fix this soon.

**Comment by kondratyev-nv** [comment]
@Kenuat I've just published new version 0.3.10 with the fix for Tavern plugin test execution. Please, update and let me know if the issue persists.

**Comment by Kenuat** [comment]
@kondratyev-nv I'm very sorry for slow response. Everything works now as expected, thank you, great work, very appreciate it.
