### ISSUE TITLE
Tests sometimes wont show code lens, nor show up in test explorer UI

### ISSUE THREAD

**Issue by marti32997** [kondratyev-nv/vscode-python-test-adapter#98]

**Comment by kondratyev-nv** [comment]
@marti32997 Thank you for the issue! Can you please provide more information on this? Screenshot, log records or project sample to reproduce would be helpful.

**Comment by deitry** [comment]
Sometimes I see no tests if there are errors in tests or imported modules - like referencing non-existing members.

Python Test Adapter Log output panel shows no errors:
```
2019-09-20T13:28:46.526Z info at 'project' [pytest runner]: Reading configuration for workspace project
2019-09-20T13:28:46.532Z info at 'project' [pytest runner]: Loading environment variables file my.env
2019-09-20T13:28:46.533Z info at 'project' [pytest runner]: Discovering tests using python path '/usr/bin/python3' in /home/user/workspace/project
```

**Comment by kondratyev-nv** [comment]
@deitry Thank you for the information! I tried to add invalid module export like

```
import some_non_existing_module

def test_some_method():
    pass
```

and it did not break the whole discovery, but the file with the invalid import was not shown in the test explorer. I will try to improve logging and add error output for such cases.

**Comment by deitry** [comment]
Thank you.
Yes, this is exactly same behaviour.

Some cases are not that obvious so I have to run pytest manually on undiscovered files. Same issue appears when imported module exist but have errors in it.

Maybe consider adding option whether to retranslate any pytest output to Output Panel?

**Comment by kondratyev-nv** [comment]
In the latest version 0.3.11 I have added discovery error reporting to the Python Test Adapter Log. This should help with the understanding of what went wrong during test collection. I will consider showing such errors more clearly, for example, in Test Explorer UI.

**Comment by deitry** [comment]
Thank you so much!
